### ISSUE TITLE
active checkbox spinnt

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#1]
in detailansicht orga:
klickt man die checkbox mehrmals hintereinander, beginnt sie zu blinken o.ä.; scheinbar löst man irgendwie eine kette von actions aus, die irgendwann aber auch wieder zur ruhe kommt

**Comment by friedrichweise** [comment]
+ [ ] hide stateTransition from detail view
+ [x] lock action during HTTP request
