### ISSUE TITLE
Als Redakteur möchte ich die Events einer Orga sehen

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#100]
... um nicht alle Event im Kopf merken zu müssen oder umständlich zu sammeln

Frage wäre: Was macht der Ausländerrat gerade alles?

- [ ] Detail View
- [ ] alle Events verlinkt

In Zukunft: Anzeige zugehöriger Events auch an anderer Stelle sinnhaft

**Comment by friedrichweise** [comment]
Works just fine.
