### ISSUE TITLE
Als Redakteur möchte ich, dass ein Ort automatisch auf einer Karte angezeigt wird

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#101]
... damit ich eine Vorschau zur Kontrolle sehe und Koordinaten nicht selbst eingeben muss

**Comment by stevereinke** [comment]
Ich habe serverseitig implementiert, dass man Geocoding-Anfragen an das Backend stellen kann. Es gibt wieder einen Token. ANsonsten lautet ein Beispiel-Request:
dev.backend.afeefa.de/api/v1/geocoding?token=[...]&address=irgendeinbeispielstring
bzw.
dev.backend.afeefa.de/api/v1/geocoding?token=[...]&street=str&zip=01309&city=Dresden&country=Deutschland
