### ISSUE TITLE
Als Redakteur möchte ich zu einem Eintrag eine Subkategorie festlegen

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#102]
... um ihn thematisch feiner zu bestimmen

- [x] nur Subcats zur ausgewählten Parent-Cat
- [x] Subcat ist optional
- [x] wenn Parent-Cat geändert -> Subcat auf null setzen
- [ ] Unit tests schreiben

**Comment by friedrichweise** [comment]
Ready for testing

**Comment by kakenbok** [comment]
Tests OK:

- [x] Parent-Kategorie ist Pflichtfeld
- [x] Keine Subkategorie-Auswahl angezeigt ohne Parent-Kategorie
- [x] Subkategorie im Form zurückgesetzt nach Änderung der Parent-Kategorie
- [x] Sub ist optional

Tests nicht OK:

- [ ] Beim Ändern der Parent-Kategorie bleibt alte Subkategorie im Model bestehen uns wird zum Server geschickt
- [ ] Sowie daraus folgend: Keine (client und serverseitige) Validierung auf Integrität (sub muss zu parent gehören)
- [ ] Ändern der Kategorie (Parent oder Sub) erzwingt keinen Abbrechen-Dialog bei Cancel

**Comment by friedrichweise** [comment]
- [ ] Validierung der Kategorien auf Serverseite

**Comment by friedrichweise** [comment]
Ich brauche ein bisschen Unterstützung beim Schreiben des Unit Test @kakenbok. Ich habe das Problem in 1cd49c4 beschrieben.
