### ISSUE TITLE
Als Redakteur möchte ich in der Kategorienauswahl die Namen der Kategorien sehen.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#104]
beim auswählen einer ober- oder unterkategorie werden direkt die technischen values als wahrnehmbare labels ausgegeben (one word in english). hier wäre die deutsche kategoriebezeichnung wünschenswert bzw sogar unbedingt notwendig, da das schon im alten backend ein großes ärgernis für die redakteure war und behoben wurde.

vlt ist es zeit für eine backend language-bibliothek, zb eine separate json mit einfachen key-value paaren.

**Comment by friedrichweise** [comment]
Short: Translations for categories

**Comment by kakenbok** [comment]
tested and found to be ok

**Comment by felixkamille** [comment]
könnte man die default option noch ausgrauen? zb so: 

```
select option[data-default] {
  color: #888;
}
<select>
  <option value="" selected data-default>select your beverage</option>
  <option value="tea">Tea</option>
  <option value="coffee">Coffee</option>
  <option value="soda">Soda</option>
</select>
```

**Comment by friedrichweise** [comment]
Einzelne `option Elemente` sind leider nicht so leicht zu stylen ohne den Default Style zu behalten.
