### ISSUE TITLE
Nach der Eingabe einer falschen URL oder beim Besuchen eines fehlerhaften Links werde ich zum Dashboard weitergeleitet und möchte hier einen Hinweis erhalten, was passiert ist (z.B. "URL ungültig" oder "Eintrag nicht vorhanden"), um nicht dumm zu sterben und zu wissen, wo das Problem liegt.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#105]

**Comment by friedrichweise** [comment]
### Test:
- [ ] undefined paths: `/qutaschUNDso`
- [ ] defined paths with undefined query parameters: `/orgas/123456780abc`

**Comment by felixkamille** [comment]
also beide varianten funzen. für `/quatschUNDso` gibt's eine sinnvolle fehlermeldung. bei `/orgas/453245sdogn` wird nur die server-message o.ä. ausgegeben. das ist noch nicht so schön. hier wäre zum beispiel etwas wie
> eine Orga mit der ID `453245sdogn` existiert nicht

**Comment by felixkamille** [comment]
das automatische schließen der error message per ESC funzt nicht, denke ich

**Comment by friedrichweise** [comment]
I changed the error message to something more detailed. For German translation we should discuss a more general approach first.

ESC key is tracked in #96

**Comment by felixkamille** [comment]
- [x] die error messages passen soweit.
- [ ] die weiterleitung kann ich allerdings nicht testen, da ich oft einfach raus fliege zum login, z.B. bei https://dev.backend.afeefa.de/orgas/194855345asd

**Comment by friedrichweise** [comment]
Das "Rausfliegen" kann nur mit den Token-Timeouts zusammenhängen. Die können in der backend-api konfiguriert werden.

**Comment by stevereinke** [comment]
Kann hier jemand das Problem nochmal detailliert erläutern?

**Comment by friedrichweise** [comment]
Ich kann das auch nicht ausreichend reproduzieren.
Vielleicht kannst du das nochmal konkretisieren, @felixkamille  ?

**Comment by kakenbok** [comment]
ich konnte es auf dem dev mehrfach herstellen, dass obwohl eingeloggt im deeplink die API token-validierung ein 401 zurück gibt. aber ich kann es nicht sicher wiederholen.

**Comment by kakenbok** [comment]
@felix, wenn das nochmal auftritt, bitte einen bug reporten. diese story ist jetzt wie folgt gelöst:

1. nicht vorhandene route -> dashboard mit hinweis
2. nicht vorhandene ressource (detail und editform) bei richtiger route -> anzeige von: "Fehler beim Laden des Eintrags 39sss31"
