### ISSUE TITLE
Bug: cancel behavior for date and time does not work properly in entry form

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#110]
- [x] cancel entry will reset date and time to old values
- [x] cancel new entry, will close entry without warning (new entry will set actual date as start date in model, which cause warning)

**Comment by kakenbok** [comment]
Ich habe jetzt das cancel-edit-entry Mixin umgearbeitet, sodass es jetzt vollständig generisch mit allen möglichen relationen (hasMany, belongsTo) sowie mit Date-Properties umgehen kann, bei denen nicht nur die Instanz selbst geändert wird sondern auch der Wert ein und derselben Instanz. Das klappt im Test sehr gut. Damit das jetzt auch für den Datepicker funktionert sind folgende Änderungen notwendig. Zuerst aber noch kurz die Arbeitsweise:

**Arbeitsweise**

Am Anfang der Route (edit, new) werden alle existierenden Relations (category, subCategory, location, contactInfo, parentOrga) sowie alle vorhandenen Date-Attribute eines Entries (date_start, date_end, updatedAt, stateChangedAt, ...) gecached, um sie beim späteren Cancel für ein Diff hinzuzuziehen.

Theoretisch - wenn der Nutzer nichts ändert, wird der Diff dann leer ausfallen.

Relations: Wenn eine Relation hinzugefügt oder entfernt wird, wird der Diff das feststellen (oldReferences != newReferences). Wenn eine Relation geändert wird (was derzeit nur bei contactInfos und locations der Fall ist) wird dies auch erkannt anhand von hasChangedAttributes(). Alle anderen Relations wie Annotatioins oder Kategorien sind bloße Zuordnungen, bei denen sich ein Relation-Objekt nicht selbst ändern (aber selbst das würde erkannt werden).

Date-Attribute: Wird ein Date komplett neu gesetzt (neue Instanz) wurde das sowieso schon erkannt. Wird nur der Zeitwert der gleichen Instanz geändert, wird ein toString()-Vergleich mit dem am Anfang gecachten Zeitwert durchgeführt. Außerdem wird festgestellt, ob ein Date vorhanden war und nun nicht mehr oder nicht vorhanden war und nun gesetzt ist.

**Anpassungen Date-Picker**

Der Date-Picker-Cancel funktioniert jetzt schon dann (und nur dann), wenn ein Event geändert wird, welches sowohl Start- als auch Enddate hat. In diesem Fall gibt es zwei gecachte Date-Objekte, die beim Diff identisch mit dem aktuellen Wert zum Zeitpunkt des Cancel sind.

Nicht funktionieren alle Fälle, bei denen der Date-Picker auf dem Model ein Date initial erzeugt, also eben auch nicht bei Event.New.

Damit das funktioniert ist es notwendig, dass der Date-Picker auf dem Model Daten nur setzt, wenn der Nutzer auch wirklich etwas geändert hat. Derzeit operiert der Picker komplett auf den Model-Properties. In Zukunft sollte er das Model dann updaten, wenn auch wirklich was geändert wurde.

Da wir ein Startdatum immer bereit stellen möchten, sollte dies nicht mehr vom Picker gesetzt werden sondern bereits in der edit bzw. new Route (z.b. routes/protected/event/new.js):
```
model() {
  const entryInstance = this.store.createRecord('event');
  entryInstance.set('date_start', new Date());
```
oder (.../edit.js):
```
model(params) {
  const entryInstance = this.store.peekRecord('event', params.event_id);
  if (!entryInstance.get('date_start')) {
    entryInstance.set('date_start', new Date());
  }
```

Ein Enddatum müsste nicht initial vorliegen, dann sollte der Picker immer einfach "gleicher Tag" sowie keine Endzeit anzeigen.

**Comment by friedrichweise** [comment]
Vielen Dank für die ausführlichen Erläuterungen.

Eine kurze Anmerkung zum Startdatum, welches automatisch gesetzt werden soll. Die angegeben Code Zeilen können wir uns sparen. Ember erlaubt Default Werte für einzelne Attribute eines Models ([Dokumentation](https://guides.emberjs.com/v2.4.0/models/defining-models/#toc_options)).

Wir können also unser Event Model folgendermaßen modifizieren:
```
export default entry.extend({
  date_start: DS.attr('date', {
    defaultValue() { return new Date(); }
  }),
  date_end:       DS.attr('date'),
  ...
```

**Comment by HagenBeelitz** [comment]
cool, dass das Abbrechen jetzt funktioniert, bin gerade dabei den Vorschlag von Friedrich auszuprobieren. Mir ist aufgefallen, dass das Speichern jetzt nicht mehr klappt und das Datum jedes mal zurück gesetzt wird, bin noch am Bug suchen.

**Comment by kakenbok** [comment]
super, hast die richtige lösung gefunden, ich hab nochmal den test angepasst und ein bisschen im verdoppelten ifelse aufgeräumt.

**Comment by HagenBeelitz** [comment]
zum Festhalten der Erkenntnisse. Versuch date_end zu löschen Nummer: 
1) date_end anlegen, wenn es gebraucht wird -> datepicker kommt damit nicht klar
2) date_end als extra Objekt Kapseln, nur auf Model speichern, wenn Änderungen -> geht nicht mit der Ember Datenstruktur
3) date_end beim Speichern und Cancel jeweils löschen und beim Aufruf der Entry-Form anlegen -> Cancel hook registriert das löschen als Veränderung des Modells -> cancel hook ist jetzt darauf hin angepasst.
