### ISSUE TITLE
Als Redakteur*in möchte ich daran gehindert werden Datum und Uhrzeiten anzugeben, welche nicht sinnvoll sind.

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#111]
Idee: Anstatt Warnungen auszugeben, lieber Nutzer*innen daran hindern falsche Daten eingeben zu können.

**Comment by HagenBeelitz** [comment]
test user input:
- [ ] end date >=  start date
- [ ] update focus on 'end date datepicker' if same day and start date is changed

**Comment by HagenBeelitz** [comment]
- [ ] start date > current date
- [ ] end date > start date
- [ ] start time != end time
- [ ] end time > start time, if same day
- [ ] start time > current time, if same day

**Comment by kakenbok** [comment]
Bug?: Wenn die Event-Zeiten nicht kompatibel sind, erscheint eine Fehlermeldung, und die Eingabe wird gelöscht. Netter wäre, die Eingabe nicht zu löschen, um ein einfaches Korrigieren zu ermöglichen.
