### ISSUE TITLE
Bug: Beim Klick auf den Button für das Start- und Enddatum öffnet sich der Datepicker nicht (er öffnet und schließt sich sofort).

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#113]
flatpickr open function does not work

**Comment by kakenbok** [comment]
hey, wenn das so steht (also nur titel ohne hinweis zum nachvollziehen), kann das nur von den leuten behoben werden, die da schon involviert waren. ich würde das gerne testen, weiß aber nicht, was los ist.

**Comment by kakenbok** [comment]
@HagenBeelitz

**Comment by kakenbok** [comment]
Haben mit random rumklicken getestet ... hat sich immer geöffnet jetzt
