### ISSUE TITLE
einheitliche formular validierung

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#115]
validierung beim ausfüllen eines formulars unterschiedlich je attribut:

- einige felder validieren clientside über HTML5 required attribute und werfen keine explizite fehlermeldung, sondern fokussieren nur das entsprechende feld

- andere felder werden serverside validiert und werfen eine richtige fehlermeldung

>> das ist ziemlich verwirrend. eine vereinheitlichung wäre hier absolut sinnstiftend. ich persönlich würde die popup message in jedem fall bevorzugen.

**Comment by kakenbok** [comment]
Kommentar aus #116:

> Kontaktinformationen - muss ausgefüllt werden
> diese meldung kommt auch, wenn ich eine kontaktperson angegeben habe. ziel ist sicherlich, telefon und email zu erzwingen. kontaktperson läuft aber in der selben feldgruppe "kontaktinformation" und ruft verwirrung hervor, wenn dann angeblich immer noch eine angabe fehlt.
