### ISSUE TITLE
fehlermeldung zu fehlender "kontaktinformation" verwirrend

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#116]
> Kontaktinformationen - muss ausgefüllt werden

diese meldung kommt auch, wenn ich eine kontaktperson angegeben habe. ziel ist sicherlich, telefon und email zu erzwingen. kontaktperson läuft aber in der selben feldgruppe "kontaktinformation" und ruft verwirrung hervor, wenn dann angeblich immer noch eine angabe fehlt.

**Comment by friedrichweise** [comment]
Should be discussed in #115

**Comment by kakenbok** [comment]
marked as duplicate and moved to #115
