### ISSUE TITLE
Als Redakteur würde ich mir in der Desktop-Ansicht Buttons zum direkten Hinzufügen einer Orga/ eines Events im linken Navigationsbereich wünschen.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#118]

**Comment by friedrichweise** [comment]
I'm going to add this to the sidebar as soon as possible. Any specific design ideas, @felixkamille ?

**Comment by friedrichweise** [comment]
![artboard](https://cloud.githubusercontent.com/assets/7392490/22421285/a48eeafe-e6e6-11e6-80a2-399995fcfaea.png)
![artboard copy](https://cloud.githubusercontent.com/assets/7392490/22421286/a48fe544-e6e6-11e6-9747-1987587f71b3.png)

**Comment by kakenbok** [comment]
sehr guter task, hab ich auch dort gewünscht. variante 1 find ich schlanker, den (+) hätte ich gern next to the titel.

**Comment by kakenbok** [comment]
jetzt wird das (+) bei hover eingeblendet. für pads ist das damit nicht zugänglich. -> pls fix
