### ISSUE TITLE
Basic Form Validation

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#12]
- [x] HTML5 required
- [x] Output Server Error message

- [x] Validierung Kategorie via Server
- [x] Validierung Mail oder Telefon für Kontaktperson via Server
- [x] Titel: required
- [x] Beschreibung: required, 150 Zeichen
- [x] Kontaktperson: required
- [x] Datum am Event: required

**Comment by friedrichweise** [comment]
- [x] new-orga
- [ ] edit-orga
- [ ] new-event
- [ ] edit-event

**Comment by stevereinke** [comment]
Backend-Validierungen:
- [ ] Validierung Kategorie via Server
- [ ] Validierung Mail oder Telefon für Kontaktperson via Server
- [ ] Titel: required
- [ ] Beschreibung: required, 150 Zeichen
- [ ] Kontaktperson: required
- [ ] Datum am Event: required

**Comment by friedrichweise** [comment]
Implemented in Frontend ✅
