### ISSUE TITLE
create and remove phraseapp translations automatically

### ISSUE THREAD

**Issue by stevereinke** [AfeefaDe/afeefa-backend-ui#127]

**Comment by friedrichweise** [comment]
Seeding and creating events only working after removing several lines from `translateable.rb`

**Comment by kakenbok** [comment]
- [ ] wird aktuell beim speichern einer orga 2mal gesynct

**Comment by kakenbok** [comment]
"Gute Arbeit!" (y)

**Comment by kakenbok** [comment]
- [x] Löschen klappt!

**Comment by kakenbok** [comment]
- [ ] dauert 100000 jahre zu lange (7 sek), async machen?

**Comment by stevereinke** [comment]
delayed job einbauen

**Comment by stevereinke** [comment]
außerdem cache einbauen und sync via delayed job machen
https://phraseapp.com/docs/guides/working-with-phraseapp/webhooks/
https://phraseapp.com/docs/api/v2/

**Comment by stevereinke** [comment]
also noch offen:
[] warum 2x?
[] update of entry should update phraseapp asynchronously

**Comment by stevereinke** [comment]
2x liegt am 2. save im monkey patch der base resource zur behandlung der nested associations bei create und update. 
das lässt sich erst mit ablösen des jsonapiresource gems lösen...
