### ISSUE TITLE
contact.person = '' => orga.contact removed

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#128]
Interessanter Fehler:

Wenn ich im Orgaformular für einen Kontakt die Person auf '' setze und speichere, dann gibt mir die API im Response die korrekt gespeicherte Orga zurück - mit der Kontakt-ID als Relationship.

Wenn ich die Orga aber neu lade, fehlt jeder Kontakt-Relationship. Offenbar führt das Setzen der Person zu '' zu einem "Ablinken" von Orga und Kontakt.

Wenn ich den alten Kontakt separat lade, sehe ich, dass er gar nicht geändert wurde, also hier noch die alte Person drin steht.

**Comment by kakenbok** [comment]
Ich konnte das jetzt noch einmal nachvollziehen, indem ich die Pflichteingabe für das Emailfeld tmp. deaktiviert habe.

1. lade event `events/123`, relation.contact_infos ist: `{type: "contact_infos", id: "457"}`
Kontakt 457 wird automatisch mit geladen und enhält alle attribute

2. Lösche alle Informationen aus Kontaktformular und speichere Event.
PATCH schickt als Kontaktrelation mit: `{type: "contact_infos", attributes: {contact_person: "", mail: "", phone: ""}, id: "457"}`

3. Server-Response mit dieser Relation: `{type: "contact_infos", id: "457"}`

4. Lade Event neu, Server-Response enthält: `data: []`

5. Lade alten Kontakt separat: `contact_infos/457`. Server schickt Stand des Kontaktes von vor dem Löschen der Attribute mit: `{mail: "alt@email.de", phone: "1234", contact_person: "", created_at: "2017-04-10T12:37:55.000+02:00",…}`

=>

* mapping zum alten kontakt geht verloren, bei leeren daten wird offenbar die relation entfernt
* alter kontakt nicht aus db gelöscht und auch nicht geändert

**Comment by kakenbok** [comment]
Jetzt sendet das Frontend eine null bei leeren contact/location. Dennoch dürfte das Problem Bestand haben.

**Comment by kakenbok** [comment]
@stevereinke Aktueller Stand: Location und Kontakt werden - wenn leer - vom Entry abgetrennt. Sehr gut. Dennoch bleiben sie persistiert und lassen sich über den contact/id bzw. location/id link noch vom API ziehen, sprich: nicht gelöscht.

**Comment by stevereinke** [comment]
gelöst mit #149

**Comment by kakenbok** [comment]
danke für die geluld. passt alles!!!
