### ISSUE TITLE
Als Redakteurin möchte ich einen Bild-Url für einen Eintrag anlegen

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#138]
- in detail view + edit view
- gleich anzeigen, wenn da oder gerade eingegeben (wie bei map)

**Comment by kakenbok** [comment]
reviewed, tested and found to be okay

**Comment by friedrichweise** [comment]
The image should be located next to the URL input. What do you think ?

**Comment by kakenbok** [comment]
we decided to put it to the same place as in the detail view.

**Comment by friedrichweise** [comment]
Maybe we should add a small “edit icon” next to the image. By clicking the icon the URL input gets focused.
