### ISSUE TITLE
Als Redakteurin möchte ich zu einem Kontakt Homepage/Facebook angeben

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#140]
- [x] UI implementation
- [x] API implementation
- [ ] API refactor `facebook` to `social_media`
- [ ] UI refactor `facebook` to `social_media`

**Comment by friedrichweise** [comment]
UI development on branch `dev-openingHours`

**Comment by friedrichweise** [comment]
When editing the links we are only validating against the URL spec. That doesn't  include the `https://` prefix. Links entered without the protocol will be opened as relative links in the DetailView. Is that a problem for our users ?

**Comment by friedrichweise** [comment]
We are adjusting the input validation.

**Comment by kakenbok** [comment]
reviewed, tested and found to be okay
