### ISSUE TITLE
500 Server error for loading todos

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#143]
Server throws 500 with the following message:
```
NameError (undefined local variable or method `state' for #<Todo:0x007fa2ea986158>):
```

**Comment by kakenbok** [comment]
yo, es muss wohl entry.state heißen. ich  hab mal ein bisschen rumgeschaut und konnte es nicht fixen. der letzte mit dem UI funktionierende commit ist der hier: https://github.com/AfeefaDe/afeefa-backend-api/commit/887160375b555993e9632de36ced2b70459c7cbe

**Comment by kakenbok** [comment]
fixed! works properly with current versions of dev
