### ISSUE TITLE
Als Redakteur*in möchte ich die Liste der Events nach vergangenen und kommenden Events filtern können

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#146]

**Comment by felixkamille** [comment]
kommende Events aufsteigend sortieren
vergangenen Events dranhängen absteigend sortieren

**Comment by kakenbok** [comment]
Leider ist der Filter noch nicht in der URL gespeichert, sodass ein Reload aus dem Modus "Vergangene Events" in den kommenden Events landet.

Reproduce:

1. show past events
2. navigate to page 13
3. hit F5

Result:

* page shows upcoming events first page
* urls still stores page 13 :-(

Expected:

* page and url show past events page 13

**Comment by kakenbok** [comment]
Es wäre gut, wenn der Link zu den Past-Events nicht so prominent auftaucht, weil diese eine sehr geringpriore Relevanz einnehmen.

**Comment by friedrichweise** [comment]
Die Option sollte als URL Paramter gespeichert werden.

**Comment by kakenbok** [comment]
Wir haben entschieden, aus den Past-Events eine eigene Route zu bauen.

**Comment by kakenbok** [comment]
@HagenBeelitz hagen kannst du nochmal durchtesten?

**Comment by friedrichweise** [comment]
Vielleicht könnte langfristig (neue Story) die Anzahl mit in der Sidebar angezeigt werden.

**Comment by felixkamille** [comment]
total genial! navigiert sich wunderbar und fühlt sich intuitiv an.
+1 für die sidebar. sofort zu sehen, wie viel kommende events wir im angebot haben, wäre klasse.
