### ISSUE TITLE
Removing annotation from Entry should remove Todo Resource

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#149]
By removing the annotation from an Entry (using `PATCH` call) the item should not be listed in the Todo Resource list.
There are database entries with an empty entry_id:

<img width="709" alt="screen shot 2017-04-28 at 21 32 12" src="https://cloud.githubusercontent.com/assets/7392490/25544299/2dba6638-2c5a-11e7-83f4-4aeb2a1de530.png">

**Comment by stevereinke** [comment]
should be done with #182

**Comment by stevereinke** [comment]
streng genommen ist das kein duplikat

**Comment by stevereinke** [comment]
aber die ursache war die gleiche wie in #128

**Comment by stevereinke** [comment]
bitte abschließend nochmal testen. danke

**Comment by kakenbok** [comment]
getested an found to be nicely working
