### ISSUE TITLE
bug: pressing publish button does not change entry.state_changed_at property

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#150]

**Comment by HagenBeelitz** [comment]
when reloading page it works -> as long user does not complain it should work

**Comment by stevereinke** [comment]
Anscheinend Caching-Problem in UI.

**Comment by kakenbok** [comment]
außerdem auch nicht: "updated_at"

**Comment by kakenbok** [comment]
fixed, tested by jens + hagen
