### ISSUE TITLE
Activate/Deactivate Entry does not work any more

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#151]
Pershaps related to abstract handling of attributes since "active" is a computed property.

**Comment by stevereinke** [comment]
active wieder einbauen

**Comment by friedrichweise** [comment]
`/orgas` and `/orgas/:id`: active attribute is `null`
`/events` and `/events/:id`: active attribute is not present

**Comment by kakenbok** [comment]
getestet. funktioniert, wie es soll. danke!!"!!!!!!!!!!!!!!
