### ISSUE TITLE
Refactor activate to publish; image adress to link

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#155]
- [x] translate validation errors to German

**Comment by friedrichweise** [comment]
Change message in alert and dialog:
````
Orga aktivieren
Soll die Orga "ABC-Tische des Umweltzentrums Dresden e. V." aktiviert werden?
````

**Comment by felixkamille** [comment]
gut soweit!
letzter Vorschlag zum "Verbergen" Prozess: bitte Änderung der Bestätigungsmeldung von "Die Orga wurde verborgen" auf "Die Orga ist nun nicht mehr öffentlich sichtbar"
