### ISSUE TITLE
Als Redakteur möchte ich meine Eingaben nicht auf einer endlos langen Seite durchführen. Weil: *nerv*

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#157]

**Comment by kakenbok** [comment]
Wenn ich ein Entry speichern möchte, welches Fehler hat, springt der Validator nur im ersten Tab an. In allen anderen Tabs wird der Request zum Server durchgestellt, wo er dann natürlich fehltschlägt.

Die Server-Response führt dann wiederum zu diesem Fehler:

```
error saving item Response {url: "/api/v1/events/788", ok: false, status: 422, statusText: "Unprocessable Entity", headers: Headers…}
app.js:16382 Uncaught (in promise) TypeError: Cannot read property '_relationIds' of null
    at app.js:16382
    at <anonymous>
```

**Comment by friedrichweise** [comment]
Kannst du bitte genauer erklären, wann der Fehler auftritt. Kanns nicht reproduzieren.

**Comment by kakenbok** [comment]
Reproduce:

1. Open Event or Orga Form
2. remove short description field's content
3. navigate to tab "Ort"
4. submit form

Result:

1. Request wird zum Server durchgestellt -> Alert

Expected:

1. Request wird durch Validator clientseitig abgefangen

**Comment by kakenbok** [comment]
bug verschoben in #213

**Comment by kakenbok** [comment]
tabs funktionieren super. (getestet)
