### ISSUE TITLE
translations migrieren

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#164]
migrate translations from old phraseapp project (connected to neos) to the new phraseapp project (connected to backend-api)

old project ID: `e989a075962418d0e05398d2fc107265` _Afeefa.de_
new project ID: `473a16f79defb1cd2d47464deb4c6008` _Afeefa gem testing_

**Comment by friedrichweise** [comment]
Läuft!

**Comment by friedrichweise** [comment]
Run the following task:
`RAILS_ENV=production bundle exec rake db:seed` in `/home/afeefa/rails/afeefa-backend-api-dev/current`

* **takes a few hours**
* write output to file

**Comment by friedrichweise** [comment]
Starting the migration (server, backend-api-dev) currently outputs the following message:
````
"Start seeding database (2017-05-21 14:13:57 +0200)."
"Cleaned up phraseapp. Deleted 0 keys."
"Seeding database finished (2017-05-21 14:14:01 +0200)."
````
Any ideas @stevereinke  ?

**Comment by stevereinke** [comment]
see db/seeds.rb on line 83:
if Rails.env.development?

migration will run only in dev mode, not in production

You can change this line or run it manually via rails console:
see line 85:
Neos::Migration.
      migrate(migrate_phraseapp: (Settings.phraseapp.active rescue false), limit: { orgas: nil, events: nil })

**Comment by stevereinke** [comment]
Hallo Friedrich, 

ich verstehe nicht, wo die Fehler auftauchen. Ich hab mal auf dem Server danach gesucht:

`[afeefa@schedar current]$ grep 'undefined method' log/*
log/production.log:F, [2016-11-04T15:24:18.674623 #19477] FATAL -- : [c80a1a28-ff56-4bba-b8fc-c9930afa20f9] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:24:25.051512 #19477] FATAL -- : [4f81f0de-00a9-49fb-8bb2-53f05f4e971c] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:16.524878 #19477] FATAL -- : [604f83a1-8d6a-4b20-81a2-3d6a5312123a] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:17.491065 #19477] FATAL -- : [56f17324-1eaf-43d6-ba15-956e1694048a] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:18.183694 #19477] FATAL -- : [74d4251c-a4a8-4af9-813f-36eccb55b061] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:26.202182 #19477] FATAL -- : [90ca3b16-082e-4993-8ff5-8be4f8671eda] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:27.292261 #19477] FATAL -- : [ca66e0a8-1050-4198-8751-e96436afb2c8] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:28.062804 #19477] FATAL -- : [4adfb3cd-8e64-4db6-ad59-fcd49d96996e] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:28.813673 #19477] FATAL -- : [87c44256-7f93-4fd7-a839-5a6a143edcd1] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:29.476132 #19477] FATAL -- : [2ee30981-a961-4b8e-8ba4-746767019259] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:30.004884 #19477] FATAL -- : [413f3044-a6b6-4a3c-99ae-6fbeae01b2b3] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:30.448443 #19477] FATAL -- : [5e296de4-a12b-4f69-a773-e06977e0c963] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:30.926613 #19477] FATAL -- : [fdb80ac3-5acd-4581-b77f-65912fbc60ba] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:F, [2016-11-04T15:26:31.458538 #19477] FATAL -- : [c1a78e3e-09e4-4c1d-83c5-2764f0a22cc8] NoMethodError (undefined method `join' for "https://dev-backend.afeefa.de":String
log/production.log:E, [2016-12-15T12:25:57.125842 #20526] ERROR -- : [7f524f86-8ac6-4d5e-b99f-4d61d6449be1] Internal Server Error: undefined method `[]' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/releases/20161214194523/app/resources/api/v1/base_resource.rb:45:in `block (2 levels) in _replace_fields'
log/production.log:E, [2016-12-15T12:26:02.432980 #20526] ERROR -- : [b8a5216e-4b5a-42c4-9a65-1bcb143007f8] Internal Server Error: undefined method `[]' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/releases/20161214194523/app/resources/api/v1/base_resource.rb:45:in `block (2 levels) in _replace_fields'
log/production.log:E, [2016-12-15T12:26:07.151070 #20526] ERROR -- : [00107c1d-bba6-495f-8c2b-8c78745b3159] Internal Server Error: undefined method `[]' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/releases/20161214194523/app/resources/api/v1/base_resource.rb:45:in `block (2 levels) in _replace_fields'
log/production.log:E, [2016-12-15T12:27:53.552895 #20526] ERROR -- : [c8c00798-457b-4b3a-9a9a-8141abc0d90b] Internal Server Error: undefined method `[]' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/releases/20161214194523/app/resources/api/v1/base_resource.rb:45:in `block (2 levels) in _replace_fields'
log/production.log:E, [2016-12-15T13:10:06.406682 #16318] ERROR -- : [e4403322-1486-4bc7-a09f-d9b39766c163] Internal Server Error: undefined method `[]' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/releases/20161215120328/app/resources/api/v1/base_resource.rb:45:in `block (2 levels) in _replace_fields'
log/production.log:E, [2017-02-01T10:25:50.966564 #8292] ERROR -- : [c5b25b94-d66c-49fe-9228-75be82adbf54] Internal Server Error: undefined method `arel_table' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/shared/bundle/ruby/2.3.0/gems/jsonapi-resources-0.9.0.beta3/lib/jsonapi/resource.rb:1143:in `block in preload_included_fragments'
log/production.log:E, [2017-02-01T16:19:11.660315 #18053] ERROR -- : [c85d4c31-89f8-4917-8302-46128d0d7bdf] Internal Server Error: undefined method `arel_table' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/shared/bundle/ruby/2.3.0/gems/jsonapi-resources-0.9.0.beta3/lib/jsonapi/resource.rb:1143:in `block in preload_included_fragments'
log/production.log:E, [2017-02-01T16:37:42.288794 #18053] ERROR -- : [5f3092b3-d8b8-4232-8b8e-482faa323bb6] Internal Server Error: undefined method `arel_table' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/shared/bundle/ruby/2.3.0/gems/jsonapi-resources-0.9.0.beta3/lib/jsonapi/resource.rb:1143:in `block in preload_included_fragments'
log/production.log:E, [2017-02-08T09:45:39.734223 #29867] ERROR -- : [f947cb9e-7b29-4950-aed2-246b54ea3836] Internal Server Error: undefined method `arel_table' for nil:NilClass /home/afeefa/rails/afeefa-backend-api-dev/shared/bundle/ruby/2.3.0/gems/jsonapi-resources-0.9.0.beta3/lib/jsonapi/resource.rb:1143:in `block in preload_included_fragments'`

Das ist alles schon alt. Kannst du mal sagen, wo du den bekommst und mir bitte die komplette Fehlermeldung inklusive stacktrace schicken?

**Comment by friedrichweise** [comment]
### Todos
- [ ] logs auf dem Server durchgehen
- [ ] Keys in der PhraseApp GUI testen
