### ISSUE TITLE
Als Redakteur möchte ich zu einem Kontakt die dort angeboteten Sprachen angeben können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#168]
mit integrierter auswahlliste (multiselect) aller weltweit verfügbaren sprachen im 2-stelligen ISO format

**Comment by friedrichweise** [comment]
- [ ] UI support
- [ ] API support

**Comment by friedrichweise** [comment]
Enabling the Materialize `select`-Element is harder than expected:
http://stackoverflow.com/questions/33704122/vuejs-materializecss-select-field

**Comment by friedrichweise** [comment]
Current development in `languageSelect`-Branch

**Comment by friedrichweise** [comment]
Merged everything into `dev` (API and UI)

**Comment by HagenBeelitz** [comment]
- [ ] Kreuze Weiß
- [ ] am weitesten verbreitete Sprachen (aus unserer lokalen Perspektive) oben anzeigen
