### ISSUE TITLE
Als Redakteur möchte ich einem Entry eine kommaseparierte Liste von Tags hinzufügen.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#169]
für events und orgas

**Comment by kakenbok** [comment]
wird vom backend noch nicht ausgegeben oder empfangen.

**Comment by friedrichweise** [comment]
Enabled tags for API in branch: `dev-enableTags`

**Comment by friedrichweise** [comment]
### Tasks
- [ ] review api implementation – @stevereinke 
- [ ] frontend validation ?
- [ ] backend validation ?

**Comment by kakenbok** [comment]
Gedanken zur Validierung: Es sollten nur Tags erlaubt sein, die im URL angezeigt werden können, sprich nummern und englische buchstaben, keine sonderzeichen oder leerzeichen.

**Comment by friedrichweise** [comment]
Merged everything into `dev`-Branch.

**Comment by kakenbok** [comment]
Oki Tags erstellt oder gelöscht. Backendvalidierung auch getestet.

**Comment by felixkamille** [comment]
die tags werden nicht über die FAPI ausgegeben

**Comment by stevereinke** [comment]
Also im dev geht das bei mir

**Comment by friedrichweise** [comment]
Nach dem Release letzte Woche auch live.

**Comment by felixkamille** [comment]
läuft super!
