### ISSUE TITLE
Deeplinks not working

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#17]
Navigate to:

https://backend.afeefa.de/orgas/412
or e.g. https://backend.afeefa.de/login

Result:

Not Found
The requested URL /orgas/412 was not found on this server.
Apache/2.2.15 (CentOS) Server at backend.afeefa.de Port 443

Expected:

Same state as when navigating using the frontend router (starting with just http://backend.afeefa.de)

**Comment by friedrichweise** [comment]
Fixed deep link problem using `.htaccess`.
But the session restore seems to have some flaws (#18)
