### ISSUE TITLE
Als Redakteur möchte ich angeben, zu welchen Attributen ich die Infos des Parententries zusätzlich anzeigen möchte.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#170]
### formulierte Anforderungen der Redaktion:
> gerne alles vererben, mit Anzeige der vererbten Inhalte im BE; Man muss Sachen raus löschen können, so dass da auch nichts mehr da steht im FE

##### Standardverhalten
_soll standardmäßig vererbt werden oder nicht?_
- Benji: Vererben als Standard, da im Regelfall sehr viele Infos vom Parent benötigt werden
- Felix: Achtung, Anwendungsfälle überschneiden sich hier!  
__A)__ Das Anlegen eines Kindes hat momentan (bzw. im alten Backend) die Intention, Eigenschaften vererben zu können, also rein organisatorisch um Pflegeaufwand zu reduzieren.
__B)__ wir haben bei der Vererbung ebenfalls die realistische Abbildung von Organisationsstrukturen im Sinn, also eher semantisch. Diese werden jedoch momentan noch gar nicht im Frontend abgebildet und spielen daher praktisch noch keine große Rolle. Ich halte diesen Aspekt perspektivisch aber für weitaus wichtiger. Hier würde ich eher gegen eine Vererbung als Standardfall plädieren.

**Comment by felixkamille** [comment]
__API__
- [ ] ...

__UI__
- [ ] ...

__Migration__
- [ ] ...

**Comment by felixkamille** [comment]
im neos werden folgende attribute vom parent ans kind AUTOMATISCH vererbt, es sei denn, man überschreibt es mit einem individuellen wert:
`["offer", "dateFrom", "dateTo", "timeFrom", "timeTo", "area", "name", "description", "mail", "web", "facebook", "phone", "subCategory", "speakerPublic", "speakerPrivate", "image", "imageType", "supportWanted", "category", "spokenLanguages"]`

**Comment by kakenbok** [comment]
Wir haben beschlossen, dass wir auf Vererbung verzichten und anstelle dessen zu einem Eintrag abspeichern, ob wir Beschreibung, Kontakt oder Location eines evtl. Parent-Entries im Frontend mit anzeigen wollen. Das DB-Feld dazu heißt aktuell (passenderweise)
 "inheritance".

**Comment by kakenbok** [comment]
Außerdem:

Kontakte und Locations werden vom Parent nur dann übernommen, wenn im Kind keine eigenen definiert wurde. Dann werden diese durch die Frontend-API transparent als eigene Eigenschaften an den Frontend-Client ausgeliefert.  D.h. es gibt immer max 1 Kontakt/Location, und es bleibt für den Client unklar, ob es die eigenen Daten sind oder die des Elternteils.

Im Kind liefert die Frontend-API als Knoten den Parent mit aus:
```
* id
* title
* description (falls im kind konfiguriert)
* short description (falls im kind konfiguriert)
```

**Comment by kakenbok** [comment]
Da die Vererbung API-seitig vollständig umgesetzt ist, besteht noch die Anforderung, dies im UI verfügbar zu machen.

- [ ] drei checkboxen je zu Kurzbeschreibung, Kontakt, Location
- [ ] es ist dabei egal ob parent da ist oder nicht, wir speichern einfach nur die notiz
- [ ] format ist `entry.inheritance = 'short_decription|contact_infos|locations'` oder `entry.inheritance = null` Beim speichern ohne Inhalt bitte `null` hinschicken und nicht empty string

**Comment by kakenbok** [comment]
Tests:

- [x] Hinzufügen und Entfernen von `short_description` bei Event
- [x] Hinzufügen und Entfernen von `short_description` bei Orga

**Comment by felixkamille** [comment]
bitte noch über die FAPI ausgeben

**Comment by felixkamille** [comment]
@kakenbok bitte noch über die FAPI ausgeben
