### ISSUE TITLE
Als Redakteur möchte ich auf der Detailseite neben dem Titel eines Eintrags einen Preview-Link zum Frontend, damit ich schnell prüfen kann, wie der Eintrag im Livebetrieb aussieht.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#171]
es gibt einen eintragslink aus dem backend ins frontend, damit der redakteur einen eintrag in realumgebung überprüfen kann

**Comment by friedrichweise** [comment]
Konfiguriert für `dev` und `production` environment.

**Comment by kakenbok** [comment]
also klappt sehr gut, falls orgas und events sich aus dem selben ID-Pool bedienen.

**Comment by kakenbok** [comment]
da sie es nicht nun: reopen :-)

`https://[dev.]afeefa.de/(orga|event)#<ID>`

**Comment by friedrichweise** [comment]
Wir brauchen hier eine UNIQUE id von der API.

**Comment by kakenbok** [comment]
```
http://afeefa.de/events/123
http://afeefa.de/orgas/123
```

**Comment by kakenbok** [comment]
hinter der ID steht ein sprechender text, und der ist erstmal egal. wir werden uns da mal was ausdenken in zukunft.

**Comment by friedrichweise** [comment]
Text am Ende wird in #219 getrackt. Dafür bräuchten wir ein API/UI Konzept.

**Comment by kakenbok** [comment]
tests:

- [ ] nur für aktivierte entries angezeigt
- [ ] /event/id
- [ ] /orga/id

**Comment by kakenbok** [comment]
tschick
