### ISSUE TITLE
Als Nutzer*in möchte ich Einträge über das Frontend hinzufügen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#174]

**Comment by stevereinke** [comment]
aus dem Slack:
Felix:
> variante a) einen backend-user namens "frontend" erstellen und so quasi die BAPI anhauen, als würde man die BUI verwenden.
> variante b) die FAPI um entsprechende methoden erweitern und ohne BAPI auskommen. redundanter code!
> finde variante *a* vielversprechender, weil wahrscheinlich weniger aufwand und kein redundanter code.

Steve:
> @felix: Zur Info: WIr schlagen vor, #174 mittels frontend api umzusetzen und die komplexität des systems mit vlalidierungen und so dem redakteur zu überlassen

Friedrich:
> Der Eintrag wird einfach ohne Validierung in die Datenbank geschrieben. Der Redakteur muss sich dann einloggen und fehlende Felder verbessern. So können Nutzer über das Frontend ohne Validierung (oder mit einfacherer Validierung) erstmal ihre Infos loswerden. Der Feinschliff erfolgt dann durch die Redaktuere.

**Comment by stevereinke** [comment]
Ich habe eine einfache Variante umgesetzt, mit der man eine Orga mit Titel und ein Event mit Titel, Start- und End-Datum anlegen kann. Das geht mittels POST auf

> /api/marketentries

Details zur Schnittstelle sollten wir noch besprechen bzw. anpassen. Aber du kannst erstmal probieren mit, diese Ressource mit dem Frontend anzusprechen.
