### ISSUE TITLE
"Veranstalter" fehlt bei Events im Verweise-Tab

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#179]
Bei Orgas ist die Parent-Orga jedenfalls vorhanden.

**Comment by stevereinke** [comment]
Jetzt steht da "keine Verweise vorhanden", obwohl der Veranstalter unter dem Titel des Events vermerkt ist.

**Comment by friedrichweise** [comment]
Passt!
