### ISSUE TITLE
Migrationsfehler: Pirnaer Tafel 4 x migriert

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#181]
Der Bug ist, dass wir die vier Duplizierungen aus NEOS jetzt so mitschleifen und demso 4 verschiedene Kontaktobjekte haben. Außerdem erhalten wir "Titel schon vergeben"

**Comment by felixkamille** [comment]
einfach an Redakteure weiterreichen, dass das im Neos noch geändert wird

**Comment by kakenbok** [comment]
Test: nur zwei von drei kindern haben den ursprünglichen parent gesetzt.

**Comment by kakenbok** [comment]
Erkärungsversuch:

Drei Tafeln sind Unterorgas mit teilweise eigenständigen Werten. Alle vier Tafeln heißen: "Familienzentrum Pirna - Pirnaer Tafel"

neos:
```
select * from afeefa_live.ddfa_main_domain_model_marketentry e
left join afeefa_live.ddfa_main_domain_model_location l
on l.market_entry_id = e.persistence_object_identifier
where e.locale = 'de' and e.name like  '%Pirnaer%'
```

api:
```
select * from afeefa_dev.orgas o
left join contact_infos c
on c.contactable_type = 'Orga' and c.contactable_id = o.id
left join locations l
on l.locatable_type = 'Orga' and l.locatable_id = o.id
where title like '%Pirnaer Tafel%'
```

**Comment by kakenbok** [comment]
Die Titel bereits vergeben - Meldung sollte besser gelöst werden, da sie  aktivierte Einträge deaktivert. Übersicht aktueller Meldungen

annotations
---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| Kategorie muss ausgefüllt werden | Event | 123 | 
| Kurzbeschreibung muss ausgefüllt werden | Event | 352 | 
| Kategorie fehlerhaft:  ist nicht erlaubt. | Event | 123 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Event | 34 | 
| Start-Datum muss ausgefüllt werden | Event | 8 | 
| Titel ist zu lang (mehr als 150 Zeichen) | Event | 3 | 
| Kurzbeschreibung muss ausgefüllt werden | Orga | 377 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Orga | 10 | 
| Titel ist bereits vergeben | Orga | 35 | 
| Kategorie muss ausgefüllt werden | Orga | 3 | 
| Kategorie fehlerhaft:  ist nicht erlaubt. | Orga | 3 |

**Comment by kakenbok** [comment]
Es gab 26 Orgas mit dupliziertem Titel, die wir daher deaktivert hatten. DIe habe ich jetzt für die Migration herausgenommen, sodass sie aktiv bleiben.

**Comment by felixkamille** [comment]
ja, ich bin daccord! aktiv schalten und annotation lassen. top!
