### ISSUE TITLE
Metadata Todos nicht aktuell nach Modifikation

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#182]
yo, wenn du die annotations eines todos entfernst, dann werden die metadata neu geladen, jedoch werden die enthaltenen numTodos leider nicht decreased.

**Comment by kakenbok** [comment]
Plus: Auch nicht beim Neuladen der ganzen App. Bleibt im alten Zustand.

**Comment by stevereinke** [comment]
@see #149

**Comment by stevereinke** [comment]
Vermutlich gleiches Problem wie bei Locations und ContactInfos: Beim Aufheben der Verknüpfung werden die Models nicht gelöscht. Das sollte mit einem dependend destroy gelöst werden.

**Comment by kakenbok** [comment]
funktioniert heute, wir wissen nicht, warum

**Comment by stevereinke** [comment]
Ich habe #128 und #149 behoben. Kann mal bitte jemand prüfen, ob damit auch dieses TIcket hier gelöst ist?

**Comment by kakenbok** [comment]
ja wir haben es geprüft. es ist nichts zu beanstanden!!! einself
