### ISSUE TITLE
Autosize textareas in tabbed entry form

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#185]
Autosize texarea

**Comment by friedrichweise** [comment]
* autosize `short_description`
* make sure that autosizing is working in inactive tabs

**Comment by kakenbok** [comment]
done. lösung: nach jedem tabchange wird auf existierende textareas gecheckt (description, short, opening hours, directions) und falls vorhanden ein autosize draufgepappt. zusätzlich wird der fall behandelt, dass die textarea für die sich nachladenden kontakt und ort auch nochmal gecheckt wird.

**Comment by kakenbok** [comment]
@friedrichweise  checkste mal? oder @HagenBeelitz
