### ISSUE TITLE
translations ausgeben

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#190]
Ein wichtiger Hauptpunkt ist die Bereitstellung der Phraseapp-Translations (inkl. Fallback für fehlende Sprache eines Attributes) für das Frontend.

Die naive Idee sieht vor, dass wir die Phraseapp-Translations lokal in einer Backend-Tabelle vorhalten und inkrementell per webhook updaten.

Dazu brauchen wir diese Tabelle und einen Webhhook-Endpoint. Der Grund für diesen lokalen Translation-Cache ist schlicht Zugriffszeit.

**Comment by foobar0112** [comment]
tz tz tz

**Comment by stevereinke** [comment]
perspektivisch asynchron via active job

**Comment by friedrichweise** [comment]
Ich bekomme aktuell folgenden Fehler:
```
Started GET "/api/marketentries?locale=en" for ::1 at 2017-06-03 13:07:31 +0200
Processing by EntriesController#index as HTML
  Parameters: {"locale"=>"en"}
...
Completed 500 Internal Server Error in 3810ms (ActiveRecord: 180.1ms)

NoMethodError (undefined method `facebook' for #<Orga:0x007fde1f7aea40>):

app/models/concerns/entry.rb:54:in `as_json'
app/controllers/entries_controller.rb:17:in `index'

```

**Comment by kakenbok** [comment]
undefined method `facebook' is fixed

für mich ist es gerade nicht möglich die verarbeitung/ausgabe der translations zu testen, da unser gem-phraseapp leer ist.

**Comment by stevereinke** [comment]
* [ ] json cachen

**Comment by friedrichweise** [comment]
Habe eben mal alles auf dem Server deployed. Aktion funktioniert:

![Screen Shot 2017-06-07 at 16.29.50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58202dfbc83da81300226bac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256454f46b7191a379e90c2958415a4ebe5d4a1d15a2add676fffc6932985619eed3675e70cf3b19a8bd8a1cb805b927995397f6fed51695bb7937ed998a473f4b001b8cab5530a1cb489a5efe4be11953a3103e35f43b.png)

Die Tabelle enthält lediglich 7 Einträge.

**Comment by friedrichweise** [comment]
Ausgeben funktioniert. Bug in #266
