### ISSUE TITLE
Wunschzettel der Redaktion für das neue Backend

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#191]
Wunschzettel der Redaktion für das neue Backend

- [x] Parent-Orga im Titel sichtbar
- [ ] Locations: bereits erstellte Locations zur Auswahl in neuen Einträgen
- [ ] Einträge bekommen ein Haltbarkeitsdatum - nach Ablauf wird automatisch eine E-Mail an den Urheber gesendet mit der Bitte zur Überprüfung der Daten
Haltbarkeitsdatum ist für Orga/ Kleinanzeige unterschiedlichen z.B.6 Monate, 3 Monate... 
- [ ] Nutzer kann Änderungen von eingetragenen Daten melden - z.B. Öffnungszeiten haben sich geändert (siehe http://www.info-compass.net/)

**Comment by felixkamille** [comment]
erst nach dem Release angehen

**Comment by friedrichweise** [comment]
Siehe Wiki!
