### ISSUE TITLE
Als Nutzer möchte ich auf Afeefa.de eine Kleinanzeige (Börseneitrag) aufgeben können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#195]
BAPI
- [ ] neues Model anlegen
- [ ] individuelles Attribut: type [offer|request]
- [ ] sonstige attribute von entry übernehmen, __AUSSER__: lange beschreibung (description), media URL, parent_orga 

Migration
- [ ] Börseneinträge aus dem neos migrieren  
`IF (offer == 1) set event.type = offer ELSE set event.type = request`

UI
- [ ] neuen Hauptabschnitt für Börseneinträge anlegen
- [ ] edit forms etc. anlegen

FAPI
- [ ] Börseneinträge ausgeben

**Comment by stevereinke** [comment]
Rückfrage: 
Was bedeutet "sonstige attribute von entry übernehmen". Bezieht sich das auf die alte DB?
