### ISSUE TITLE
Als Redakteur möchte ich zu einem Event ein Eventformat angeben können, damit schneller klar wird, was die Besucher*innen erwartet.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#198]
damit geben wir das Format der Veranstaltung an, daher bitte als multiselect mit folgenden Optionen:

_Vortrag, Lesung, Kongress, Seminar, Workshop, Demo, Konzert, Film, Ausstellung, Demo_

**Comment by friedrichweise** [comment]
Erstmal Konzept.
