### ISSUE TITLE
Scrollbar in entry title

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#201]
![image](https://cloud.githubusercontent.com/assets/491557/26153745/29acf2c4-3b0d-11e7-8417-1ed91a17b24b.png)

**Comment by kakenbok** [comment]
Der Titel-Text ist bei ungünstiger Screeneinstellung im Desktop leider abgeschnitten.

![image](https://cloud.githubusercontent.com/assets/491557/26252075/8965cc38-3caf-11e7-864b-63fbde5a34bb.png)

**Comment by kakenbok** [comment]
Ich bin sehr dafür, dass der `white-space: nowrap;` herausgenommen wird und das ganze dann so aussieht:

![image](https://cloud.githubusercontent.com/assets/491557/26252749/66154860-3cb1-11e7-8c84-029ad6107951.png)

**Comment by kakenbok** [comment]
@felixkamille

**Comment by felixkamille** [comment]
ja, das clipping mit '...' kann weg und der header kann ruhig den platz nehmen, den er braucht. ist ja momemtan bei der mobile ansicht auch schon so.

**Comment by kakenbok** [comment]
yeah! tested
