### ISSUE TITLE
Als Redakteur möchte ich angeben, ob ein Eintrag besondere Unterstützung benötigt.

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#203]
Backend liefert bereits: `support_wanted`

An/Aus-Element.

**Comment by felixkamille** [comment]
das frontend formular bietet derzeit noch die möglichkeit, eine beschreibung zur benötigten unterstützung einzugeben (freitext). im alten neos system wird das zwar nicht gespeichert, aber es dient als hinweis für die redakteure. der aspekt, details über die unterstützungsbedarfe zu erfassen, wird nochmal spannend!
