### ISSUE TITLE
migration: fehlende short description sollte eine annotation auslösen "Kurzbeschreibung fehlt"

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#204]
Zusätzlich sollte ein UPDATE oder CREATE nicht mit leerer short_description zulässig sein.

**Comment by friedrichweise** [comment]
Jetzt bekommen wir  "558" Einträge, die als Todos eingestuft werden (und deshalb auch nicht veröffentlich werden). @felixkamille Wie verfahren wir damit ?

**Comment by friedrichweise** [comment]
Ausnahme: Alle Orgas/Events ohne `short_description` sollen trotzdem aktiviert werden.

**Comment by stevereinke** [comment]
AKtuell werden alle Einträge aktiviert, auch wenn diese nicht valide sind. SOllen diese wirklich nur aktiviert werden, wenn sie gültig sind oder keine short_description haben? Das wäre wieder AUfwand, das umzubauen...

**Comment by felixkamille** [comment]
Ok, fassen wir nochmal zusammen:
- 500+ todos wegen fehlender kurzbeschreibung ist zu hart
- die migrierten daten ohne kurzbeschreibung waren im alten neos system veröffentlicht und können jetzt nicht einfach auf unbestimmte zeit geblockt werden
- die kurzbeschreibung muss ein pflichtfeld bleiben, da diese als qualitätsmerkmal forciert werden und die lange beschreibung auf lange sicht wegfallen soll

neue wunschvorstellung:
- die kurzbeschreibung bleibt ein pflichtfeld
- bei der migration werden invalide einträge (ohne kurzbeschreibung) trotzdem auf aktiv gesetzt, damit sie wie gehabt ans frontend ausgeliefert werden können, da die einträge an sich ja brauchbar sind
- sobald der redakteur einen eintrag ohne kurzbeschreibung anfasst (zb nur zum ändern einer mail) greift die validierung wieder und er wird zur erstellung einer kurzbeschreibung gezwungen

@stevereinke ist es möglich, die ausnahme innerhalb der migration zu pflanzen und auch einträge ohne kurzbeschreibung einfach auf active zu setzen und somit (im rahmen der migration) die validierung zu umgehen?

**Comment by kakenbok** [comment]
- [x] Migration lässt jetzt alle Entries mit falschen Kurzbeschreibungen aktiv
- [x] Dekativieren leider nicht möglich wegen weil die Validierung nur während der Migration ausgehebelt wird
- [ ] Nicht-aktive Entries aus NEOS werden bei erfolgreicher Validierung auf active gesetzt??????

**Comment by kakenbok** [comment]
oki done. das problem mit dem deaktivieren bleibt. es wäre cool, wenn die validierung für das deaktivieren ausser gefecht gesetzt wuerde.

**Comment by friedrichweise** [comment]
- [ ] deaktivieren ignoriert validierung

**Comment by stevereinke** [comment]
ich habe einen fix in dev gepusht

**Comment by friedrichweise** [comment]
Funktioniert nicht mit Events:
````
Started PATCH "/api/v1/events/3445" for 127.0.0.1 at 2017-06-02 12:21:44 +0200
Processing by Api::V1::EventsController#update as JSON
  Parameters: {"data"=>{"id"=>"3445", "type"=>"events", "attributes"=>{"active"=>false}}, "id"=>"3445"}
  User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`uid` = 'friedrich@afeefa.de' LIMIT 1
   (0.1ms)  BEGIN
  Event Load (0.3ms)  SELECT  `events`.* FROM `events` WHERE `events`.`id` = 3445 ORDER BY `events`.`id` ASC LIMIT 1
  Orga Load (0.3ms)  SELECT  `orgas`.* FROM `orgas` WHERE (`orgas`.`title` IS NULL OR (`orgas`.`title` != 'ROOT-ORGA')) AND `orgas`.`id` = 1 LIMIT 1
  Orga Load (1.5ms)  SELECT  `orgas`.* FROM `orgas` WHERE `orgas`.`title` = 'ROOT-ORGA' LIMIT 1
  Category Load (0.5ms)  SELECT  `categories`.* FROM `categories` WHERE `categories`.`id` = 1175 LIMIT 1
   (0.2ms)  ROLLBACK
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 165 LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Completed 422 Unprocessable Entity in 477ms (Views: 0.3ms | ActiveRecord: 3.9ms)
````

**Comment by friedrichweise** [comment]
Und auch nicht für Orgas:

````
Processing by Api::V1::OrgasController#update as JSON
  Parameters: {"data"=>{"id"=>"7329", "type"=>"orgas", "attributes"=>{"active"=>false}}, "id"=>"7329"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`uid` = 'friedrich@afeefa.de' LIMIT 1
   (0.1ms)  BEGIN
  Orga Load (0.3ms)  SELECT  `orgas`.* FROM `orgas` WHERE (`orgas`.`title` IS NULL OR (`orgas`.`title` != 'ROOT-ORGA')) AND `orgas`.`id` = 7329 ORDER BY `orgas`.`id` ASC LIMIT 1
  Orga Load (0.3ms)  SELECT  `orgas`.* FROM `orgas` WHERE (`orgas`.`title` IS NULL OR (`orgas`.`title` != 'ROOT-ORGA')) AND `orgas`.`id` = 1 LIMIT 1
  Orga Load (0.3ms)  SELECT  `orgas`.* FROM `orgas` WHERE `orgas`.`title` = 'ROOT-ORGA' LIMIT 1
  Category Load (0.3ms)  SELECT  `categories`.* FROM `categories` WHERE `categories`.`id` = 1175 LIMIT 1
  Orga Exists (0.8ms)  SELECT  1 AS one FROM `orgas` WHERE `orgas`.`title` = BINARY 'Lauftreff' AND (`orgas`.`id` != 7329) LIMIT 1
  Orga Exists (0.9ms)  SELECT  1 AS one FROM `orgas` WHERE `orgas`.`title` = BINARY 'Lauftreff' AND (`orgas`.`id` != 7329) LIMIT 1
   (0.1ms)  ROLLBACK
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 165 LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Completed 422 Unprocessable Entity in 34ms (Views: 0.4ms | ActiveRecord: 4.0ms)
````

**Comment by kakenbok** [comment]
- [x] migration aktiviert wieder die entries. war typo. commit #3a18906a6df6b7aff7b288b11b204ac84017c97b

**Comment by kakenbok** [comment]
added before_validation and set `do_not_validate` to true if user tries to deactivate entry

**Comment by felixkamille** [comment]
gut so. die einträge sind jetzt zwar trotz fehlender shorty aktiv, aber die redakteure werden mit >600 todos überhäuft. wir haben uns mit steve geeinigt, auch die annotation für fehlende kurzbeschreibungen zu umgehen und bei der migration also keine todos aus diesen einträgen zu machen. die falle beim öffnen eines eintrags bleibt.

**Comment by kakenbok** [comment]
gut, fehlende short_description löst keine annotation aus und lässt eintrag aktiv. bitte testen.

**Comment by kakenbok** [comment]
fix ist hier (wegen fehlender ref): https://github.com/AfeefaDe/afeefa-backend-api/commit/bc4fa8e5f681b19b88cebdb038bca054f98d51dd#diff-113f8aff3770eec7f325499f14bb7e1dR263

**Comment by felixkamille** [comment]
oops: #254
