### ISSUE TITLE
Wunschzettel Release des Redaktionsteams

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#209]
hier bitte eine liste: 

https://docs.google.com/document/d/1g8TzjizROKsH6uq5oropQw2uwjcE2PgMVmcZNN-yP4k/pub

**Comment by kakenbok** [comment]
stand 24.5.:

* eingebundene Grafik sollte ordentlich zugeschnitten oder zumindest positioniert werden können
* Parent-Orga im Titel sichtbar
* Vererbung: gerne alles vererben, mit Anzeige der vererbten Inhalte im BE; Man muss Sachen raus löschen können, so dass da auch nichts mehr da steht im FE
* Locations: bereits erstellte Locations zur Auswahl in neuen Einträgen
* Einträge bekommen ein Haltbarkeitsdatum - nach Ablauf wird automatisch eine E-Mail an den Urheber gesendet mit der Bitte zur Überprüfung der Daten
* Haltbarkeitsdatum ist für Orga/ Kleinanzeige unterschiedlichen z.B.6 Monate, 3 Monate...
* Nutzer kann Änderungen von eingetragenen Daten melden - z.B. Öffnungszeiten haben sich geändert (siehe http://www.info-compass.net/)
* Wenn man im alten BE wegen Zeitüberschreitung ausgeloggt wird und man gerade dabei war, einen Beitrag zu verfassen, wird nichts vom bisherigen Fortschritt gespeichert, man darf den gesamten Beitrag noch einmal schreiben. Das sollte nicht mehr passieren.
* bei Anmerkungen: es sollte ein Freitext möglich sein
* man kann einen Eintrag als Entwurf speichern, dass soll die Ticketes die ich sonst in der waffle habe ersetzen
* E-Mails aus Redaktionspostfach mit Backend verbinden
* Überschrift für Feld “Kurzbeschreibung” ->ändern in “Beschreibung”
* Überschrift für Feld “Beschreibung” -> ändern in “Langbeschreibung” oder “mehr Informationen” oder “zusätzliche Beschreibung”
* “Automatisches” Versenden von E-Mail wenn ich einen Eintrag veröffentlicht habe

**Comment by friedrichweise** [comment]
Konzept im Wiki erarbeiten.
