### ISSUE TITLE
Als Redakteurin möchte ich in Listen schneller zwischen Orga und Event unterscheiden können.

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#210]
- [x] Kalender (Tag + Monat) wie bei Facebook
- [x] Schöne Visualisierung für Orgas, z.B. Bippel
- [x] Ermittlung aller wichtigen Attribute, die in den Listen sinnvoll gleich mit angezeigt werden
- [x] Aktivierungsstatus durch Hintergrund o.a. kommunizieren
- [x] evtl. Direktlink zum Event-Veranstalter oder zur Parent-Orga (nur mit API-Support realisierbar, also erstmal nur Konzept machen)
- [x] Spaltenlayout prüfen

**Comment by friedrichweise** [comment]
Nicht zwingend für das Release notwendig.

**Comment by kakenbok** [comment]
jedoch mittlerweile für backend2 so umgesetzt!
