### ISSUE TITLE
Social Media Input Field broken

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#211]
event edit kontakt

**Comment by friedrichweise** [comment]
<img width="649" alt="screen shot 2017-05-18 at 13 47 06" src="https://cloud.githubusercontent.com/assets/7392490/26200857/8d57b35e-3bd0-11e7-884a-772548309f95.png">

Kann ich leider nicht reproduzieren.

**Comment by kakenbok** [comment]
Kein Inhalt:

![image](https://cloud.githubusercontent.com/assets/491557/26201679/748d4a10-3bd4-11e7-8567-695972e6ca2f.png)

**Comment by kakenbok** [comment]
oha, wie wir in der addon-button-bar sehen, haben wir einen adblocking-fall, weil das element #socialMedia heißt :dancing_women:

**Comment by friedrichweise** [comment]
Adblocker für `localhost` abschalten ;)
