### ISSUE TITLE
Configure log rotate

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#212]
Configure log rotate for all files in: 
* `/home/afeefa/rails/afeefa-backend-api-dev/shared/log `
* `/home/afeefa/rails/afeefa-backend-api/shared/log `

Keep them for 30 days. Rotate daily.

**Comment by Stunkymonkey** [comment]
configs are written
but i am testing it the next days

**Comment by Stunkymonkey** [comment]
got errors, but i will just suppress them. they occured, because no file existed to be rotated
but it's working
