### ISSUE TITLE
Speichern in Folgetab hebelt Validierung aus

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#213]
Reproduce:

1. Open Event or Orga Form
2. remove short description field's content
3. navigate to tab "Ort"
4. submit form

Result:

1. Request wird zum Server durchgestellt -> Alert

Expected:

1. Request wird durch Validator clientseitig abgefangen

**Comment by friedrichweise** [comment]
Nutze jetzt `v-show` anstatt von `v-if`. Dadurch bleiben die Elemente im DOM, vee-validate wirft keine Exception und die Client-Validierung sollte problemlos klappen.

**Comment by kakenbok** [comment]
tested and found to be okay
