### ISSUE TITLE
Als Redakteur möchte ich nicht, dass vergangene Events noch als Todo markiert werden.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#214]

**Comment by kakenbok** [comment]
Well, ich habe einen Filter eingebaut, der alle vergangenen Events nicht mit annotations versieht. Hier die aktuelle Statisktik:

select distinct(detail), entry_type, count(detail)
from annotations
group by detail, entry_type
order by entry_type

annotations
---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| Kurzbeschreibung muss ausgefüllt werden | Event | 8 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Event | 6 | 
| Kurzbeschreibung muss ausgefüllt werden | Orga | 299 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Orga | 10 | 
| Titel ist bereits vergeben | Orga | 26 | 
| Kategorie muss ausgefüllt werden | Orga | 2 |

**Comment by kakenbok** [comment]
@stevereinke  kannst du hier evtl. einen test schreiben? ich fass im slack gleich nochmal meine vielen optimierungen der migration zusammen.

**Comment by stevereinke** [comment]
@kakenbok für zu kurze bzw. fehlende short_description habe ich jetzt migration tests geschrieben
kannst du die migrationsoptiomierungen nochmal zusammenfassen bzw. einen link zum slack hier reinkopieren?

**Comment by felixkamille** [comment]
@stevereinke existiert hierzu, also vergangene events nicht mehr zu todos zu machen, nun also ein test?
