### ISSUE TITLE
Als Nutzer möchte ich beim Wechseln zwischen den Tabs der Bearbeiten-Maske nicht immer wieder hochgescrollt werden.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#215]
relevant auf kleineren desktops, auf denen der untere inhalt eines tabs nur durch scrollen erreichbar ist. hat man runtergescrollt, verschwinden titel und evtl ein foto aus dem bildschirm, aber die tabs bleiben sichtbar und können also noch verwendet werden. klicke ich auf ein tab, wird störenderweise aber immer wieder nach oben gescrollt.

**Comment by kakenbok** [comment]
die tabs der bearbeiten-maske verschwinden mit backend2 vollständig.

**Comment by kakenbok** [comment]
die tabs der bearbeiten-maske verschwinden mit backend2 vollständig.
