### ISSUE TITLE
migration: von eltern vererbte attribute müssen bei den kindern gefüllt werden, da wir keine vererbung mehr haben

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#216]
innerhalb der migration muss folgendes passieren:
- einträge ohne titel bekommen den titel ihrer eltern gesetzt und zwar nach dem schema "ELTERNTITEL #N"  
z.B. _German Lessons for Refugees #4_
- einträge ohne kategorie/ unterkategorie bekommen den wert ihres parents gesetzt

**Comment by felixkamille** [comment]
wir haben jetzt viele "Kein Titel" einträge im neuen backend. das sind alles alte kindeinträge, die im alten system den titel vom parent geerbt haben. komischerweise haben viele dieser einträge im neuen backend keinen parent mehr. was ist hier mit der hierarchie-migration passiert?

**Comment by kakenbok** [comment]
erledigt mit #222

**Comment by kakenbok** [comment]
@felixkamille welche haben keinen parent mehr?

**Comment by kakenbok** [comment]
@felixkamille Könntest du bitte testen, ob alles chic ist?

**Comment by felixkamille** [comment]
keinen parent haben:

https://dev.backend.afeefa.de/orgas/1695 (wahrscheinlich ein deutschkurs unter einer alten sammelorga)

https://dev.backend.afeefa.de/orgas/1919 (wahrscheinlich ein deutschkurs unter einer alten sammelorga)

https://dev.backend.afeefa.de/orgas/1862 (keine ahnung, evtl. eine bib zweigstelle)

https://dev.backend.afeefa.de/orgas/1937 (eigentlich german lessons for refugees)

https://dev.backend.afeefa.de/orgas/1775 (eigentlich german lessons for refugees)

https://dev.backend.afeefa.de/orgas/1694 (eigentlich german lessons for refugees)

https://dev.backend.afeefa.de/orgas/1755 (eigentlich german lessons for refugees)

https://dev.backend.afeefa.de/orgas/2275 (eigentlich german lessons for refugees)

https://dev.backend.afeefa.de/orgas/1726 (eigentlich rugby cricket e.V.)

*viele davon waren früher börseneinträge. warum die kinder von GLFR nicht zugeordnet wurden, wäre interessant herauszufinden. prinzipiell können all diese einträge aber auch vernachlässigt werden und einfach so bleiben, da sie nicht mega wichtig noch aktuell sind.*

**Comment by kakenbok** [comment]
bitte nochmal testen, nachdem die migration durchlief

**Comment by felixkamille** [comment]
dana's GLFR sind alle korrekt migriert mit einem schönen parent und 10 kindern. arabische leitkultur. die SLUB hat noch einen ausgeblendeten parent-eintrag mit allen 6 zweigstellen als kinder. das ist noch eine altes hilfskonstrukt für vererbungen. hierfür müsste dem eintrag mal eine kurzbeschreibung gegeben werden, die dann von allen kindern mitverwendet werden können.
