### ISSUE TITLE
Als Redakteur möchte ich die Elternorganisation und den Veranstalter in der langen Liste suchen können

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#218]
Sprich: Benutzung von `vue-multiselect` für `parentOrga`

**Comment by friedrichweise** [comment]
### Test
- [ ] Orgas und Events
- [ ] Neuer Eintrag
- [ ] bestehenden Eintrag bearbeiten
- [ ] keine parentOrga, parentOrga entfernen

**Comment by kakenbok** [comment]
Ich finde den Workflow zum Entfernen nicht so geil. Man muss die Taste ENTF drücken, was der Nutzer eigentlich nicht weiß, da der selektierte Wert beim öffnen des Popups leider nicht auto-gescrollt wird.

Hier wünsche ich mit entweder einen Default wie "Kein Veranstalter" oder einen Löschen-Button.

**Comment by kakenbok** [comment]
Flatpickr und Multiselect schmeißen Warnungen im Dev-Tool. Das hat wohl mit Änderungen in der neuesten JS-Engine zu tun, und wir müssen auf Fixes hoffen.

**Comment by friedrichweise** [comment]
Gelöst, in dem ich die Auswahl mehrerer Elemente zulasse, das Limit jedoch auf 1 setze. Dadurch bekommen wir schicke "Tags" mit einem "X" zum entfernen.
Alle anderen Wege wären glaube ich ähnlich „hacky“ gewesen. Und so nutzen wir die bereits bekannte UI der vue-multiselect Komponente.

**Comment by kakenbok** [comment]
:yes:
