### ISSUE TITLE
Als Nutzer möchte ich in der Frontend URL den Namen des Eintrags erkennen

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#219]
Planned in #171:
```
http://afeefa.de/events/123-markos-schoenstes-event
http://afeefa.de/orgas/123-eine-tolle-orga
```

Backend-UI hat alle Informationen, um diesen LInk darzustellen. Das Frontend muss ihn dann noch sinnvoll entgegennehmen.

**Comment by felixkamille** [comment]
im FE erledigt und deployt. fehlt nur noch die anpassung des preview links in der BUI. dazu hier die slugify(), die ich im frontend verwende:
```
return text.toString().toLowerCase()
 .replace(/\s+/g, '-')           // Replace spaces with -
 .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
 .replace(/\-\-+/g, '-')         // Replace multiple - with single -
 .replace(/^-+/, '')             // Trim - from start of text
 .replace(/-+$/, '');            // Trim - from end of text
}
```
und die ganze URL ist dann sinngemäß:
`var path = [project|event] + '/' + entry.id + '-' + slugify(entry.name)`

**Comment by felixkamille** [comment]
eigentlich duplicate mit #379. einfach mit schließen dann, wenn es erledigt ist.

**Comment by friedrichweise** [comment]
Getestet für: **backend.afeefa.de ➡ afeefa.de**
Bei **backend.afeefa.de ➡ leipzig.afeefa.de** wird die richtige URL ausgegeben. Das Frontend hat bei jedoch den Eintrag nicht geladen.

**Comment by friedrichweise** [comment]
Anmerkung zur Umsetzung:
ESLint wurde für die Implementierung der regulären Ausdrücken deaktiviert. So konnte ich den identischen Code wie das Frontend verwendung.

**Comment by felixkamille** [comment]
läuft auch bei leipzig! man muss nur das richtige passwort eingeben ;)

**Comment by kakenbok** [comment]
getestet und code gesehen!

**Comment by felixkamille** [comment]
Läuft alles.
