### ISSUE TITLE
Als Redakteur möchte ich die Beschreibung einer Orga/eines Events in ein Eingabefeld schreiben, damit ich einfachen Überblick behalte.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#22]
Als Redakteur möchte ich die Beschreibung in ein Eingabefeld schreiben, damit ich einfachen Überblick behalte.

**Comment by kakenbok** [comment]
fragen: wie lang darf der text werden. zur zeit 150.
