### ISSUE TITLE
Als Redakteur:in möchte ich fortdauernde Events nach Enddatum und einmalie Events nach Startzeit sortiert bekommen

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#220]

**Comment by kakenbok** [comment]
@HagenBeelitz ich habe nochmal den sortierfilter angepasst, sodass fortdauernde events, die in der zukunft beginnen, auch noch nach date_start angezeigt werden. kannst du bitte nochmal testen?

**Comment by felixkamille** [comment]
@kakenbok passt so! habe es getestet. schöne sache!
