### ISSUE TITLE
skip validation on entry.deactivate

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#221]
Wir haben per Ausnahme eine Menge aktiver aber nicht valider Entries (Kurzbeschreibung fehlt). Wir würden solche Entries gerne deaktiveren können, ohne erst die Kurzbeschreibung hinzuzufügen.

**Comment by kakenbok** [comment]
fixed mit #204

**Comment by felixkamille** [comment]
bekomme eine ui error msg mit "internal server error" beim deaktivieren von https://dev.backend.afeefa.de/events/908

**Comment by kakenbok** [comment]
ist ein anderes thema, kurzzeitige misskonfiguration apache

**Comment by kakenbok** [comment]
nochmal getestet: klappt
