### ISSUE TITLE
Eintrag kann bei Migration sub_category ohne parent_category bekommen

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#223]
Bei der Migration erhält die "Bibliothek Weixdorf" eine `sub_category_id` aber keine `category_id`.

**Comment by kakenbok** [comment]
scheint jetzt zu gehen, kein entry in db mit subcategory aber ohne category

**Comment by friedrichweise** [comment]
Mit folgenden Query für Orgas und Events getestet:
```
SELECT title, sub_category_id, category_id
FROM events
WHERE sub_category_id IS NOT NULL AND category_id IS NULL
```
