### ISSUE TITLE
Add db migration for translation_caches table

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#228]
Following errors:
````
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'translation_caches.cacheable_type' in 'where clause': SELECT `translation_caches`.* FROM `translation_caches`

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'afeefa_dev.translation_caches' doesn't exist: SHOW FULL FIELDS FROM `translation_caches`):
````

**Comment by foobar0112** [comment]
Kommt drauf an, welches Projekt man laufen lässt, die Migration gibt es nur einmal: im `afeefa-backend-api` Projekt, die frontend-api nutzt die Tabelle dann nur… ist ja ein und das selbe Modell.

Fix: Also Migrations des backends ausführen, dann sollte es gehen.

**Comment by friedrichweise** [comment]
Dafür müsste der Branch `20170523_joschka_190_translations-api` noch in den `dev` Branch gemerged werden. Kann ich das ohne Bedenken machen ?

**Comment by kakenbok** [comment]
nee gibt merge konflike :-/

**Comment by kakenbok** [comment]
ist gemergt und hat geklappt tabelle ist da.

`rake db:migrate` sowie `RAILS_ENV=test rake db:migrate' das gleich bei `seed`
