### ISSUE TITLE
missing parent orga after migration

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#229]
etliche orgas oder events haben nach der migration keinen parent mehr

144 orgas und 183 events

**Comment by kakenbok** [comment]
ich gehe ein bisschen von einer racecondition aus. die kinderentries werden evtl. vor den parent orgas initialisiert.

**Comment by kakenbok** [comment]
```
select entry_id from afeefa_live.ddfa_main_domain_model_marketentry where parent_entry_id is not null
```

```
select * from afeefa_dev.orgas where legacy_entry_id in (
"5890bac3cfca9",...
) and (parent_id is null or parent_id = 2)
```

```
select * from afeefa_dev.events where legacy_entry_id in (
"5890bac3cfca9",...
) and (parent_id is null or parent_id = 2)
```

**Comment by kakenbok** [comment]
jetzt haben wir noch 3 events ohne parent, weil deren parent ein event war, was wir derzeit nicht erlauben "veranstalter"

@stevereinke kannst du mal die releations der entries fixen? irgendwie wildwuchs gerade. wegen "acts_as_tree" können events über `:parent` nur events entgegennehmen aber keine orgas. und in der events_resource steht noch `:orga` im grunde kann `parent_event` erstmal raus, wir haben dafür kein gutes konzept bisher.

**Comment by stevereinke** [comment]
@kakenbok das geht nicht so einfach, weil acts_as_tree ja annimmt, dass es sich um einen homogenen baum handelt. darum gibt es orga als extra relation

ist das denn aktuell ein problem? bisher nutzen wir doch auch die orga association...

**Comment by kakenbok** [comment]
es gab hier ein missverständnis bei `parent` für events.

`parent_id` - übergeordneter parent
`orga_id` - veranstalter

`parent_id` war leer, `orga_id` nicht. habe meine änderung zurückgerollt, sodass `orga_id` jetzt gesetzt wird.

**Comment by kakenbok** [comment]
@HagenBeelitz oder @friedrichweise 

Könnt ihr bitte testen, dass folgende (Stichprobe) Events mit Parent nach der Migration auch einen Parent haben: 

`select entry_id from afeefa_live.ddfa_main_domain_model_marketentry where type = 2 and parent_entry_id is not null`

und orgas:

`select entry_id from afeefa_live.ddfa_main_domain_model_marketentry where type = 0 and parent_entry_id is not null`

**Comment by friedrichweise** [comment]
Getestet mit folgenden Queries:
```
SELECT legacy_entry_id FROM orgas WHERE parent_orga_id != 1;
SELECT legacy_entry_id FROM events WHERE parent_event_id != 1;
```
