### ISSUE TITLE
Eventkategorien von Serienevents nicht migriert

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#230]
Es fehlt die Kategorie "eventseries" mit den Unterkategorien "iwgr" und "political-education"

123 Events erhalten daher keine Kategorie und dazu auch jeweils Annotations.

**Comment by kakenbok** [comment]
select distinct(detail), entry_type, count(detail)
from annotations
group by detail, entry_type
order by entry_type

---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| Kategorie muss ausgefüllt werden | Event | 123 | 
| Kurzbeschreibung muss ausgefüllt werden | Event | 352 | 
| Kategorie fehlerhaft:  ist nicht erlaubt. | Event | 123 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Event | 34 | 
| Start-Datum muss ausgefüllt werden | Event | 8 | 
| Titel ist zu lang (mehr als 150 Zeichen) | Event | 3 | 
| Kurzbeschreibung muss ausgefüllt werden | Orga | 377 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Orga | 10 | 
| Titel ist bereits vergeben | Orga | 35 | 
| Kategorie muss ausgefüllt werden | Orga | 3 | 
| Kategorie fehlerhaft:  ist nicht erlaubt. | Orga | 3 |

**Comment by kakenbok** [comment]
@felixkamille und @stevereinke ich weiß nicht, ob ihr eine andere abmachung hattet, ich habe die fehlende kategorie jetzt erstmal erstellt, sodass diese ordentlich gesetzt werden.

**Comment by kakenbok** [comment]
---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| Kurzbeschreibung muss ausgefüllt werden | Event | 352 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Event | 34 | 
| Start-Datum muss ausgefüllt werden | Event | 8 | 
| Titel ist zu lang (mehr als 150 Zeichen) | Event | 3 | 
| Kurzbeschreibung muss ausgefüllt werden | Orga | 377 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Orga | 10 | 
| Titel ist bereits vergeben | Orga | 35 | 
| Kategorie muss ausgefüllt werden | Orga | 5 |

**Comment by felixkamille** [comment]
ja, das ist ok so! prinzipiell hätten wir auf diese events (internationale wochen gegen rassismus) auch verzichten und einfach nicht migrieren können. sei's drum! ich mach zu.
