### ISSUE TITLE
Als Redakteur möchte ich die zeitlichen Infos in der Eventliste effizienter wahrnehmen können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#233]
Designvorschlag: Unterstreichen der Datumsangaben
![image](https://user-images.githubusercontent.com/1052429/26871291-ffd163ec-4b72-11e7-9f66-476cf064c5fe.png)

**Comment by friedrichweise** [comment]
siehe  #210
