### ISSUE TITLE
Eventzeit zwei Stunden zu frueh

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#234]
![image](https://user-images.githubusercontent.com/1052429/26923383-36525fdc-4c42-11e7-86f3-4373c99ab81f.png)

original: https://afeefa.de/#entry=58ed204f4ff90
falsch: https://dev.afeefa.de/#entry=58ed204f4ff90

**Comment by felixkamille** [comment]
![image](https://user-images.githubusercontent.com/1052429/26923808-986c2fb2-4c43-11e7-8df3-1eabbf2f7efe.png)

https://dev.afeefa.de/#entry=59101ad0d8f0b
https://afeefa.de/#entry=59101ad0d8f0b

**Comment by HagenBeelitz** [comment]
wenn beispielsweise ein Event am 08.06 stattfindet, kein Startdatum, aber ein Enddatum mit 16Uhr hat sieht es in der Datenbank so aus:

**Comment by kakenbok** [comment]
Das sind die richtigen Zeitstempel für ein Event, dass keine Startzeit aber eine Endzeit am selben Tag hat. Ob eine Zeit angezeigt wird, hängt am Flag: `has_time_start`. Das Datum wird auf der Clientmaschine in die lokale Zeitzone übersetzt und zeigt bei uns dann auf den gleichen Tag. Wie das etwa in UK (UTC) aussieht, kann ich nicht sagen, weil nicht getestet, aber ich würde erwarten, dass es einen Tag zu früh beginnt ohne Anfangszeit und am Folgetag um 14 Uhr endet. Es macht Sinn, dass wir unsere Zeiten im Client nochmal explizit für die Zeitzone "Berlin" konvertieren.

Für das Frontend werden die Zeitstempel schon durch die F.API im "Berlin"-Format als normaler String geliefert (also nicht als Zeitstempel), hier sollte es gar keine Probleme haben. Wenn wir davon ausgehen, das unser Backend nur bei uns betrieben wird, sollte es auch keine Probleme geben. Stell doch mal deine Rechner-Zeitzone auf London. Was kannst du berichten?
