### ISSUE TITLE
Als Besucherin möchte ich bei bestimmten Einträgen Informationen des übergeordneten Eintrag mit angezeigt bekommen.

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#235]
- [x] F.API liefert
- [ ] ~~F.UI zeigt entsprechend an, möglicherweise werden eigene Daten in die des Parents eingemerged (oder auch zusätzlich angezeigt)~~

**Comment by kakenbok** [comment]
F.API liefert das jetzt mit aus:

```
inheritance {
  short_description: false,
  contact_infos: true,
  locations: false
}
```

**Comment by felixkamille** [comment]
F.API sollte die vererbung interpretieren und die daten für die F.UI entsprechend vorbereiten >> #249
