### ISSUE TITLE
parent relation ausgeben

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#238]

**Comment by kakenbok** [comment]
events: `.hostOrgaId`
orgas: `parentOrgaId`

**Comment by felixkamille** [comment]
heißt der einfachheit halber erstmal immer `parentOrgaId`, egal ob `orga.parentOrgaId` oder `event.parentOrgaId`

**Comment by felixkamille** [comment]
läuft und wird im frontend verarbeitet.
