### ISSUE TITLE
Als Redakteur möchte ich zu jeder Annotation Kategorie und Freitext selbst wählen

### ISSUE THREAD

**Issue by KopierKatze** [AfeefaDe/afeefa-backend-ui#24]
make annotations about the reason why an entry is deactivated mandatory

**Comment by kakenbok** [comment]
unclear requirement -> closed

**Comment by kakenbok** [comment]
@KopierKatze any idea what this ticked was meant for?

**Comment by kakenbok** [comment]
- [x] Show reason in todos list
- [x] Show reason in detail view

Still open:

- [ ] Describe reason while adding Todo
- [ ] Make it possible to add more than 1 annotation per category

**Comment by stevereinke** [comment]
siehe attribut message an der annotation

**Comment by friedrichweise** [comment]
### Test
- [ ] Erstellen neuer Annotations (mit, ohne Detailtext)
- [ ] Bearbeiten bestehender Annotations
Dabei bitte überprüfen, ob der Annotationeintrag in der Datenbank aktualisiert wird, und keine neue Annotation erstellt wird.

**Comment by kakenbok** [comment]
bitte abnehmen
