### ISSUE TITLE
Inheritance bei der Migration überabeiten

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#240]
Bei der Migration gibt es keine gesetzten inheritance Flags für Einträge ohne parentOrga.

**Comment by kakenbok** [comment]
betrifft (betraf) die hier:

orgas
---
| title | legacy_entry_id | parent_orga_id | inheritance | 
| - | - | -: | - | 
| Bücherzelle der TU Umweltinitiative | 5818eb09235d6 | 1 | contact_infos | 
| Der Runde Tisch  „Versorgung traumatisierter Geflüchteter in Dresden und  Umgebung“ sucht Unterstützung für traumatisierte Geflüchtete. | 58c0418746d8a | 1 | contact_infos | 
| Women* refugee meeting | 556e1d2f2a5e3 | 1 | contact_infos | 
| „Deutsch sofort“ und „Deutsch qualifiziert“ | 586d2a4f1e4e1 | 1 | contact_infos | 
| Kleiderladen der Heilsarmee | 5570b8db255b3 | 1 | contact_infos | 
| Begegnungstreff Café Halva | 57cf0d231a352 | 1 | contact_infos | 
| Regionalkoordination Flüchtlingssozialarbeit Altstadt/Plauen | 556e1d2dcbb43 | 1 | contact_infos | 
| Regionalkoordination Flüchtlingssozialarbeit Cotta | 556e1d2db8b1b | 1 | contact_infos | 
| Regionalkoordination Blasewitz/Schönfeld-Weißig/Loschwitz | 556e1d2e60423 | 1 | contact_infos | 
| Regionalkoordination Neustadt/Klotzsche/Pieschen | 556e1d2e48238 | 1 | contact_infos | 
| felix test ini | 57476ef089d26 | 1 | contact_infos | 
| www.deutschstunde.eu | 575571ea4d07e | 1 | contact_infos | 
| Integrationskurse [Struktureinheit] | 586f8e211f6cc | 1 | contact_infos | 
| Bürgerbündnis Flüchtlingshilfe Südost | 57437bd657cc2 | 1 | contact_infos | 
| Caritas (AWO) | 56353b72eae0e | 1 | contact_infos |

**Comment by kakenbok** [comment]
Flags für Orgas mit Parent werden auch weiterhin gesetzt, etwa dieser hier:

orgas
---
| inheritance | legacy_entry_id | id | created_at | updated_at | title | description | short_description | parent_orga_id | state | state_changed_at | category_id | sub_category_id | media_url | media_type | support_wanted | for_children | certified_sfr | legacy_entry_id | migrated_from_neos | tags | inheritance | 
| - | - | -: | - | - | - | - | - | -: | - | - | -: | -: | - | - | -: | -: | -: | - | -: | - | - | 
| short_description|contact_infos | 557c50fb18ce6 | 743 | 2017-06-07 15:39:23 | 2017-06-07 15:40:08 | Fußballspielen - ZMO | Jeden Mittwoch (außer Ferienzeit und Feiertage) von 18.00
bis 19.00 Uhr in der Turnhalle der 12. Grundschule. | \N | 736 | inactive | 2017-06-07 15:39:23 | 346 | 336 | http://i0.wp.com/zmo-jugend.de/WordpressNeueSeite/wordpress/wp-content/uploads/2015/10/zmo-transparen-fullt.png?w=481 | image | 0 | 0 | 0 | 557c50fb18ce6 | 1 |  | short_description|contact_infos |

**Comment by friedrichweise** [comment]
Funktioniert wunderbar.
