### ISSUE TITLE
Beim Erstellen eines Eintrags möchte ich nach Auswahl der parentOrga die inheritance checkboxen auswählen und vererbte Inhalte erkennen.

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#241]
- [x] laden der parentOrga
- [x] anzeigen der checkboxen
- [x] verbergen, wenn parentOrga abgewählt
- [x] anzeigen der  short description des parents (EditView)
- [x] wenn der parent die vererbten merkmale nicht besitzt, bsp. keine kurzbeschreibung hat, kann diese nicht per flag ausgewählt werden
- [x] die vererbten Informationen sollten im DetailView erkennbar sein
- [x] Kurzbeschreibung ist immer required

**Comment by friedrichweise** [comment]
Guter Stil, @kakenbok:
https://github.com/AfeefaDe/afeefa-backend-ui/commit/407037252a40d791e368df74b30d196be5ca3554

**Comment by friedrichweise** [comment]
Hier könnten wir eine clevere Lösung einbauen. Die ganzen if-else nerven irgendwie:
https://github.com/AfeefaDe/afeefa-backend-ui/commit/5c2b368930c5c89fcc57b8f64e962aaf3c5795d4

**Comment by friedrichweise** [comment]
Hier gibts ne Menge Edge Cases. Ich würde das erstmal zum Test freigeben. Du findest sicher noch ein zwei Problemchen...

**Comment by friedrichweise** [comment]
Mehr Logik sollte in das Model des contactInfos gepackt werden.

**Comment by friedrichweise** [comment]
Nicht Teil des 0.6 Sprints. Sollte aber zeitnah umgesetzt werden.

**Comment by kakenbok** [comment]
oha ein monolog-issue.

**Comment by friedrichweise** [comment]
Passt soweit. Wenns uns stört, passen wir es an.
