### ISSUE TITLE
Nach dem Entfernen der parentOrga müssen alle inheritance flags auf false gesetzt werden

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#243]

**Comment by kakenbok** [comment]
Wir haben nochmal diskutiert und festgestellt, dass es theoretisch wegen Event -> Event  und Orga -> Event parallel mehrere Eltern-Einträge geben kann. Wir haben entschieden, dass wir uns zunächst bei der Wiederverwendung nur auf Orga -> Event und Orga -> Orga beziehen, da wir den anderen Fall auch noch gar nicht anbieten. Demzufolge wird jetzt im Backend `inheritance` auf null gesetzt, wenn keine Parent Orga vorhanden ist. Für die Parent-Event-Relation gibt es keine Auswirkungen.

**Comment by friedrichweise** [comment]
Funktioniert. Eine Vererbung kann trotz leeren contactInfo Objekt bestehen. Aber das ist ja irgendwie gewollt.
