### ISSUE TITLE
migrate neos entry timestamps

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#245]

**Comment by kakenbok** [comment]
nach `cap dev deploy` waren die timestamp noch im alten format.

@stevereinke kann es sein, dass bei deploy nicht geseeded wird? das hab ich jetzt mal manuell angestoßen.

**Comment by kakenbok** [comment]
Felix check mal, die Timestamp sollten jetzt funken und die Originaldaten beinhalten.

**Comment by felixkamille** [comment]
jo läuft und werden schon im frontend angezeigt
