### ISSUE TITLE
bug: Veranstaltunge, welche nur eine Endzeit haben, werden in der Entry Detail gerade so dargestellt: Donnerstag 08. Juni - 17:05 Uhr

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#246]

**Comment by kakenbok** [comment]
Wo ist der Bug? Bzw: Was würdest du richtigerweise erwarten für diesen Fall?

**Comment by felixkamille** [comment]
ja, das frage ich mich auch. @HagenBeelitz

**Comment by felixkamille** [comment]
`8. Juni um 10:00` nur start-time
`8. Juni von 10:00 bis 17:05` start-time + end-time
`8. Juni bis 17:05` nur end-time
