### ISSUE TITLE
Vererbung in FAPI verarbeiten, inkl. Übersetzungen und fallback

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#249]
- [x] kurzbeschreibung zusammenfügen (parent + child)
- [x] contact infos
  - falls wiederverwendung gewünscht...
  - wenn kind keine hat, komplett vom parent nehmen (falls verfügbar, sonst nichts)
  - wenn kind welche hat, merge für jedes einzelne contact-attribut (bevorzugt vom kind nehmen, lücken mit parent füllen)

**Comment by friedrichweise** [comment]
Ist beides mehr oder weniger ordentlich in 
https://github.com/AfeefaDe/afeefa-frontend-api/commit/53d8c948a347058891ddbcb42614b9a8747732dc
und
https://github.com/AfeefaDe/afeefa-frontend-api/commit/1e3a37388bb2fd8a305431970abe28d7e319475c
implementiert.
Wir müssen in dieser Logik jedoch noch Übersetzungen berücksichtigen. Hier bräuchten wir erstmal ein Konzept (@felixkamille ). Was geschieht zum Beispiel, wenn die Kurzbeschreibung vererbt wird, aber der Parent die Kurzbeschreibung nicht in der angeforderten Sprache hat ?

**Comment by friedrichweise** [comment]
Im Zweifelsfall soll immer die Sprache der Vererbung vorgezogen werden.

**Comment by kakenbok** [comment]
erstmal nicht relevant
