### ISSUE TITLE
Vererbung für location wieder ausbauen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#250]
die genaue Usability im Backend Formular ist noch unklar und wahrscheinlich sehr aufwändig; da die Redakteure vorher auch keine Locations wiederverwenden konnten, nehmen wir die Funktion erstmal wieder raus.

- [x] Hagen Haken wieder raus
- [ ] Attribut innerhalb entry.inheritance kann der Ordnung halber auch entfernt werden

**Comment by friedrichweise** [comment]
Aus UI entfernt.

**Comment by friedrichweise** [comment]
Wir lassen die Vererbung in der API drin. In der UI wird es aber vorerst keine Location Vererbung geben. Also kein Hagen Haken für den Location Tab.
*(Bei der aktuellen Migration tritt der Fall einer Location Vererbung sowieso nicht auf.)*
