### ISSUE TITLE
Facebook integration CORS error

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#252]
afeefa.de is not allowed origin

**Comment by felixkamille** [comment]
unter welcher route erreiche ich die fb events jetzt eigentlich?
`https://dev.afeefa.de/api/facebook_events?token=zP4uja4yFmnPWZeCVsLU` funzt nicht

**Comment by friedrichweise** [comment]
Die `Access-Control-Allow-Origin`-Header werden jetzt von der backend-api je nach Origin gesetzt. Sollte soweit passen.
