### ISSUE TITLE
Als Redakteur möchte einen Überblick über fehlerhafte Felder nach der Migration bekommen.

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#254]
Wir möchten nun für „alle“ Edge-Cases bei der Migration eine Annotation generieren. Das erzeugt uns zwar ~600 Todo's, trotzdem halte ich diese Information für notwendig. An diese Informationen kommen wir nach der Migration nicht mehr so leicht ran.
Folgende Todo's:

- [x] eine ordentliche Liste mit den zu erstellenden Annotations formulieren (z.B. "Fehlende Kurzbeschreibung") und diese den AnnotationCategories zuordnen.
- [x] diese Annotations bei der Migration generieren
- [x] Attribut `generatedBySystem` in UI verwenden
- [x] einen Filter in die Backend-API basteln `/todos?filter[category]=2` (nach ID der AnnotationCategory)
- [x] die Todo Liste in der Backend-UI nach AnnotationCategory filterbar machen.

**Comment by friedrichweise** [comment]
Erste UI Implementierung im Branch `dev-filterAnnotations`

**Comment by stevereinke** [comment]
Können wir als Namen für den Filter annotation_category_id festlegen? Das würde mir Arbeit beim Mapping ersparen...

**Comment by friedrichweise** [comment]
Bei der Konzeption der Annotations bitte beachten: Wir filtern nur nach AnnotationCategory. Vielleicht ist die Kategorie "Migration nur teilweise erfolgreich" ein bisschen zu allgemein gefasst.

**Comment by felixkamille** [comment]
annotations 

benötigte Annotation categories:
- entlang der validation
  - Titel ist zu lang
  - Titel bereits vergeben
  - Kurzbeschreibung fehlt
  - Kurzbeschreibung zu lang
  - Hauptkategorie fehlt
  - Startdatum fehlt
  - Unterkategorie passt nicht zur Hauptkategorie

maintenance annotations
- bildquelle ungültig

noch zu fixende annotations, die es nicht mehr geben sollte:
- kategorie fehlerhaft
- kategorie nicht erlaubt

**Comment by felixkamille** [comment]
![image](https://user-images.githubusercontent.com/1052429/27129909-4f3d1246-5104-11e7-96e3-f8f86955ca32.png)
Beispiel des neuen Schemas. Die Redakteure wissen hier: Bei dem Eintrag gibt es etwas zu tun (klar, weil es ja ein TODO ist) und zwar hinsichtlich der Kontaktdaten (das ist so ungefähr der detailgrad, wie ein radakteur in seinem kopf die aufgabe kategorisiert). Alle Details (die sehr vielfältig sein können) kommen in die details des annotation und können für vermerke genutzt werden, die den konkreten redaktionsprozess betreffen.

**Comment by friedrichweise** [comment]
* User icon in tuqiose

**Comment by friedrichweise** [comment]
Kann getestet werden.

**Comment by HagenBeelitz** [comment]
Der Annotation Filter funktioniert gut.

**Comment by friedrichweise** [comment]
* Die Annotation "Start Datum fehlt" wird nicht vergeben, obwohl es Events ohne gibt:
```
SELECT title, id FROM events
WHERE `date_start` IS NULL
```
* Die Annotation "Hauptkategorie fehlt" wird auch nicht vergeben:
```
SELECT id, title FROM orgas
WHERE `category_id` IS NULL
```

**Comment by friedrichweise** [comment]
Getestet mit Dump von 2017-06-16

**Comment by friedrichweise** [comment]
Alle Annotations werden ordnungsgemäß vergeben.
