### ISSUE TITLE
If canceling an entry, inheritance checkboxes (short description and contact info)  should be checked if there are changed and reset to the start state

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#258]

**Comment by HagenBeelitz** [comment]
same problem for adding parent entry

**Comment by friedrichweise** [comment]
Drei Probleme habe ich gefunden:

### 1. Ändern der parentOrga

### 2. Ändern des Inheritance flag der short_description

### 3. Laden und direktes Verlassen der Edit Seite
