### ISSUE TITLE
Als Redakteur möchte ich schnell auf dem Dashboard suchen

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#259]
Eine Suche auf dem Dashboard (ohne Auswirkung auf die URL params)

**Comment by friedrichweise** [comment]
https://github.com/AfeefaDe/afeefa-backend-ui/commit/d1a0a0af8cfa435cc33bfe4dd41714454cf63b82

**Comment by felixkamille** [comment]
total stark!

**Comment by HagenBeelitz** [comment]
Voll gut.
Kleiner Bug: wenn Eintrag gelöscht wird, kann dieser noch über die Suche gefunden werden.
