### ISSUE TITLE
Proper Migration of old Translation Data

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#261]
im alten neos backend werden aktuell noch neue einträge eingepflegt. diese übernehmen wir ins neue backend über die migration auf basis eines aktuell dumps. ein problem bleibt: die alten neos einträge werden derzeit nicht mehr mit dem alten phraseapp project gesynct. (übersetzungen werden derzeit aber eh nicht erstellt).

folge: es gibt nach der migration (daten + translations) einträge im neuen backend, die sich noch nicht im neuen phraseapp project wiederfinden.

lösung: ein maintenance prozess, der überprüft, ob alle einträge im neuen backend einen zugehörigen eintrag im phraseapp haben. falls nicht, muss der erstellt werden.

**Comment by friedrichweise** [comment]
Kurz: DB und PhraseApp synchron halten.

**Comment by friedrichweise** [comment]
1. Analyse!

**Comment by stevereinke** [comment]
Eigentlich tut das neue backend das doch automatisch, wenn man einen Eintrag bearbeitet. Diesen Mechanismus könnte man doch benutzen, oder?

**Comment by stevereinke** [comment]
Bei der Migration wurde für jedes ausgefüllte Attribut in der Hauptsprache auch ein Key im neuen Phraseapp Repo erzeugt. Damit ist das Problem vom Tisch.
