### ISSUE TITLE
JSON File Cache für erhöhte Performance

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#267]
die F.API liefert keine Übersetzungen aus, obwohl diese in der Caching Table korrekt drin sind. Setzt man zurück auf den commit `93d6513859bc03fa97731e8ced2f451dfa119f50` (noch ohne JSON File Cache), dann werden die translations korrekt über die F.API ausgeliefert.

**Comment by friedrichweise** [comment]
Wir haben ein bisschen Git-Akrobatik betrieben und die erste Implementierung des Caches in den Branch `dev-broken` verschoben. Übersetzungen werden jetzt wieder ausgegeben. Trotzdem sollte der Cache bald wieder in Aktion gebracht werden, da die Ladezeiten unerträglich lang sind.

**Comment by friedrichweise** [comment]
Siehe #278

**Comment by stevereinke** [comment]
BÄM!
Ich hab das mal gefixt und die Geschwindigkeit ist geil!
Erster Aufruf (Daten rendern) ca. 5-7s, zweiter dann < 500ms!!!
Das habe ich auf dev installiert und erstmal für de, en und ar durchgeklickt. Die sind also schnell, der Rest beim ersten Aufruf noch langsam, so die Theorie.

**Comment by kakenbok** [comment]
ich sage mal, ist gelöst. code hab ich selbst viel geschrieben, kann also nur gutes über die qualität sagen.
