### ISSUE TITLE
Neos Migration: Schritt 2b lahmt bei aktiver Phraseapp Migration

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#269]
**passierte erst nach UNSEREM [merge](https://github.com/AfeefaDe/afeefa-backend-api/commit/ddfe55f5fedfa87e9f2211a6b85a01873e669d32) EURER migrations.rb**

Durch Setzen von Settings.phraseapp.active = true wird die migration in schritt 2b seeeehr langsam. ohne phraseapp migration läuft's mit lichtgeschwindigkeit durch. wie kann das zusammenhängen?

**Comment by friedrichweise** [comment]
Läuft!
