### ISSUE TITLE
Fix encoding issue with MySQL

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#271]
Wir können keine Emojis (und möglicherweise andere Sonderzeichen) in die Datenbank speichern:

````
Internal Server Error: Mysql2::Error: Incorrect string value: '\xF0\x9F\x8C\xBD' for column 'detail' at row 1: INSERT INTO `annotations` (`annotation_category_id`, `entry_type`, `entry_id`, `detail`) VALUES (496, 'Orga', 18999, 'Test~+323🌽') /Users/friedrichweise/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
````

**Comment by foobar0112** [comment]
Hier wird es ganz schön beschrieben: um es ordendlich zu machen, auch mit Rails, müsste man aber den MySQL Server neu starten, das geht bei uberspace nicht…
https://www.railsmachine.com/articles/2017/05/19/converting-a-rails-database-to-utf8mb4.html

**Comment by friedrichweise** [comment]
https://blog.crusy.net/utf8mb4-auf-uberspace/

**Comment by friedrichweise** [comment]
Ist mit dem Serverumzug erledigt.

**Comment by Stunkymonkey** [comment]
also uberspace hat ne alte mysql version, die unterstützt kein utf8

um die neuere version nutzen zu können gibt es jetzt einen zugang in:
`/home/afeefa/.my.mariadb.cnf`
das ist eine seperate datenbank, die allerdings nicht so schnell ist

beim Serverumzug müssen wir nichts bedenken, da keiner eine SQL-Software von vor 2011 installieren will
