### ISSUE TITLE
externe Event-Quellen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#279]
- DRK Dresden https://www.drk-dresden.de/angebote/kinder-jugend-und-familie/kinder-und-familienprojekt-yoco/veranstaltungskalender/
- Quartiersmanagement Johannstadt http://www.qm-johannstadt.de/events/2017-06/

**Comment by kakenbok** [comment]
Iris wird uns einen RSS Feed bereitstellen, um die Events von genderkalender.de zu integrieren.

realisiert über TYPO3 und folgender Kalender Extension: https://typo3.org/extensions/repository/view/cal
