### ISSUE TITLE
Kategorienliste vermischt

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#281]
Ahmad:
> bei Kategorien werden die Kategorien und Subkategorien in einer Liste angezeigt und die Unterkategorieliste ist leer

**Comment by felixkamille** [comment]
konnte es nicht reproduzieren. könnte ein ladebedingtes problem sein.

**Comment by friedrichweise** [comment]
Kann ich auch nicht reproduzieren.

**Comment by felixkamille** [comment]
reproduzieren: einfach mal schnell schnell machen und nicht warten bis alles geladen ist. manchmal hakt's dann aus und die liste ist voll.
![image](https://user-images.githubusercontent.com/1052429/27857456-08410072-6172-11e7-93e3-54339e9d22c2.png)

**Comment by friedrichweise** [comment]
Laut Ahmad ist das nur nach dem __rausschmeißen__ passiert. Ich konnte es eben auch nicht reproduzieren. Somit schließe ich das Ticket erstmal.

**Comment by friedrichweise** [comment]
Meine Vermutung: Inkonsistenter Cache State
Die in der Komponente "EntryEdit" verwendete Resource gibt eine unvollständige Liste (fehlendes `parent_category`) zurück.

**Comment by stevereinke** [comment]
is das ein ui issue? oder gibt es da ein todo an der api?

**Comment by kakenbok** [comment]
bitte testen

**Comment by friedrichweise** [comment]
Kann ich nicht mehr reproduzieren.
