### ISSUE TITLE
😤   Die Backend-UI Session ist nicht stabil

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#282]
Ahmad + Johanna:
> Das backend wirft mich nach 5-10 Minuten wieder raus wenn ich auf etwas klicke

**Comment by friedrichweise** [comment]
Das liegt wahrscheinlich nicht am Timeout. Ein Token ist mehrere Stunden gültig. Das Backend scheint jedoch veraltete, invalide Token an den Server zu senden.

**Comment by friedrichweise** [comment]
Folgende Beobachtungen:
* in der Backend-API sollte unter `config/initializers/devise_token_auth.rb` die Option `  config.change_headers_on_each_request` auf `true` gesetzt werden. Nur so können wir das Problem im dev-Mode lokal reproduzieren. Generell halte ich es für falsch, die Token Generierung vom Env. abhängig zu machen. Aber das ist eine andere Diskussion...
* wir speichern die Token aktuell im 'LocalStorage' des Browsers. Dadurch ist er schonmal für alle Tabs der Domain verfügbar. Im Commit https://github.com/AfeefaDe/afeefa-backend-ui/commit/a9508fe41afd364c7e7a8caead6cb375c585f955 wird dieser nun über die Tabs hinaus synchronisiert. Vorher hat Tab 1 kein Gebrauch von dem in Tab 2 erhaltenen Token gemacht.

**Comment by felixkamille** [comment]
in dev.backend.afeefa.de komme ich gar nicht mehr rein. sofort "session abgelaufen"

**Comment by friedrichweise** [comment]
Das kann ich nicht reproduzieren.

**Comment by friedrichweise** [comment]
✅  
reproduziert:

```
ok ich versuche es einmal zu skizzieren: 1. login
2.ich gehe auf todos
3. ich filtere todos auf z.b. titel doppelt vergeben (tap 1)
4. es werden mir todos angezeigt und ich öffne in einem neuen tap (tap 2) ein todo
noch ist alles gut ich kann in beiden taps hin und her gehen
5. ich öffne einen dritten tap von z.b. einem anderen todo aus der gefilterten liste aus tap 1 und ich fliege raus (anmeldeseite) erscheint
```

**Comment by friedrichweise** [comment]
Das Problem lag meiner Meinung nach nicht am Client-Code. Lokal konnte ich das Problem nach 271d14a nicht mehr reproduzieren. Lediglich auf dem Server (dev und live Umgebung) waren weiterhin betroffen. Heute habe ich die Batch Request Throttle Time auf __25s__ gesetzt: 
```
config.batch_request_buffer_throttle = 25.seconds
```
Meine Vermutung: Einige Requests dauern auf dem Server länger als die ursprünglich angegebenen 5s. Somit wurde der neue Token nach dem Batch Request nicht ordnungsgemäß übertragen.

**Comment by friedrichweise** [comment]
Lokal kann ein Rausschmiss wieder reproduziert werden:
1. `config.change_headers_on_each_request = true`
1.  Einloggen
1. Orga auswählen
1. Parent der Orga in neuem Tab öffnen

**Comment by friedrichweise** [comment]
Erneuter Hotfix: Die token sind sehr lange gültig: https://github.com/AfeefaDe/afeefa-backend-api/commit/53dfee33204fb691e4d5fe14b08737d9a25fb8f9

**Comment by stevereinke** [comment]
Auch hierfür müsste mal eine richtige Lösung erarbeitet werden...

**Comment by kakenbok** [comment]
- [x] Fixed, validate_token kehrte mit 304 zurück (Etag), weswegen Browser alte Token nutzte

**Comment by kakenbok** [comment]
bitte testen

**Comment by friedrichweise** [comment]
Keine weiteren Probleme bekommen. Ich schließe dieses Ticket deshalb.
