### ISSUE TITLE
Vorschau-Button bei vergangenen Events rausnehmen

### ISSUE THREAD

**Issue by foobar0112** [AfeefaDe/afeefa-backend-ui#291]
der Vorschau-Button führt ins leere, da vergangene Events in F.UI nicht angezeigt werden

**Comment by friedrichweise** [comment]
Ich möchte die Logik, ob ein Eintrag im Frontend angezeigt wird, nicht in der Backend-UI spiegeln. Somit müsste diese Info als Attribut am Eintrag hängen.

**Comment by stevereinke** [comment]
backend api dev branch liefert upcoming: true/false

**Comment by kakenbok** [comment]
bug: upcoming ist als POST property eines events angelegt, was dazu führt, dass sich die API beschwert. es lassen sich derzeit keine events speichern.

**Comment by kakenbok** [comment]
bug (API): upcoming-attribut wird nicht nach update mit geliefert

**Comment by stevereinke** [comment]
fixed

**Comment by kakenbok** [comment]
klappt
