### ISSUE TITLE
Suche: add OR filter in api, make locations and contact infos for search accessible

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#293]
ich möchte Anfragen machen wie:
http://localhost:8080/api/v1/entries?filter[title]=testORentries?filter[street]=Nossen
Ergebnis: Einträge in denen test als Titel ODER Nossen als Straße Vorkommen

**Comment by felixkamille** [comment]
wir haben die überarbeitung der suche mal ein neues ticket geschmissen, siehe #307
@HagenBeelitz kannst du bitte mal versuchen, das nachzuvollziehen und sagen, ob du damit zufrieden bist? oder alles unklar?

**Comment by HagenBeelitz** [comment]
passt :)
