### ISSUE TITLE
Area Deployment auf Live

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#300]
- [ ] alle Dresdner Einträge auf `area=dresden` setzen
- [ ] Nutzer auf `area=dresden | bautzen` zuweisen
- [ ] bautzner daten importieren (import script + entries.csv)

**Comment by friedrichweise** [comment]
Bitte die Tickets ein bisschen aussagekräftiger formulieren.

**Comment by friedrichweise** [comment]
Wurde (__ungünstigerweise__) direkt auf dem `dev` Branch entwickelt. Um die Dev Umgebung wieder lauffähig zu machen, müssen folgende DB-Änderungen durchgeführt werden:

### 1. Orgas anpassen
```
UPDATE orgas
SET area = 'dresden'
WHERE id != 1;
```

### 2. Events anpassen
```
UPDATE events
SET area = 'dresden'
```

### 3. User anpassen
```
UPDATE users
SET area = 'dresden'
```

**Comment by foobar0112** [comment]
zum kopieren:
```
UPDATE orgas SET area = 'dresden' WHERE id != 1;
UPDATE events SET area = 'dresden';
UPDATE users SET area = 'dresden';
```
