### ISSUE TITLE
Beim Wechseln von Monaten spinnt der DatePicker

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#302]

**Comment by friedrichweise** [comment]
![pasted_image_at_2017_07_07_12_39_pm_360.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58202dfbc83da81300226bac/125516c66e82c728ace21e0d46f895893787879686e4be44a162f180161477227e3bf37c4fd5b417ee10445256300ef12e5b5944eee59b6be4e96625d91819e7c3685775933812a9ec8a1abe53b9728d4785b6e88c4bc3e06b37fb99cd1e604a5a45d0b50877b29359cb59fc4ae5445ca0173160ef77307b468653.png)

**Comment by kakenbok** [comment]
scheint jetzt wieder zu gehen
