### ISSUE TITLE
Lange Strings werden nicht validiert

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#303]
Lange Strings beim Erstellen eines Eintrags werden nicht validiert. Es kann zu folgenden Fehler kommen:

```
Internal Server Error: Mysql2::Error: Data too long for column 'web' at row 1: INSERT INTO `contact_infos
```

**Comment by HagenBeelitz** [comment]
Entscheidung keine Begrenzung für Zeichenlänge einzuführen

**Comment by stevereinke** [comment]
Folgende Felder habe ich nicht angepasst, diese müssten vlaidiert werden:
    # change_column :contact_infos, :phone, :string, limit: 1000
    # change_column :contact_infos, :fax, :string, limit: 1000

Folgende Feldlängen habe ich definiert:

    change_column :annotation_categories, :title, :string, limit: 1000

    change_column :categories, :title, :string, limit: 1000

    change_column :contact_infos, :mail, :string, limit: 1000
    change_column :contact_infos, :contact_person, :string, limit: 1000
    change_column :contact_infos, :web, :string, limit: 1000
    change_column :contact_infos, :social_media, :string, limit: 1000
    change_column :contact_infos, :spoken_languages, :string, limit: 1000

    change_column :events, :title, :string, limit: 1000
    change_column :events, :public_speaker, :string, limit: 1000
    change_column :events, :media_url, :string, limit: 1000
    change_column :events, :tags, :string, limit: 1000
    change_column :events, :area, :string, limit: 1000

    change_column :locations, :lat, :string, limit: 1000
    change_column :locations, :lon, :string, limit: 1000
    change_column :locations, :street, :string, limit: 1000
    change_column :locations, :placename, :string, limit: 1000
    change_column :locations, :city, :string, limit: 1000
    change_column :locations, :district, :string, limit: 1000
    change_column :locations, :country, :string, limit: 1000
    change_column :locations, :directions, :string, limit: 1000

    change_column :orgas, :title, :string, limit: 1000
    change_column :orgas, :media_url, :string, limit: 1000
    change_column :orgas, :tags, :string, limit: 1000
    change_column :orgas, :area, :string, limit: 1000

    change_column :roles, :title, :string, limit: 1000

    change_column :translation_caches, :title, :string, limit: 1000

    change_column :users, :email, :string, default: '', null: false, limit: 1000
    change_column :users, :encrypted_password, :string, default: '', null: false, limit: 1000
    change_column :users, :reset_password_token, :string, limit: 1000
    change_column :users, :forename, :string, limit: 1000
    change_column :users, :surname, :string, limit: 1000
    change_column :users, :area, :string, limit: 1000

**Comment by friedrichweise** [comment]
* für das Attribut `contactInfo.phone` habe ich eine Limitierung auf 1000 Zeichen gesetzt

**Comment by friedrichweise** [comment]
Ich habe aber noch nicht so ganz verstanden, wie wir das Problem jetzt gelöst haben. 1000 ist einfach groß genug und Redakteure erreichen das sowieso nicht?
Denn der Server wirft weiterhin 500 wenn das Limit überschritten wird.

**Comment by stevereinke** [comment]
so is die lösung, ja ;-)
alternativ kann man mit mehr auf wand eine bessere lösung erarbeiten ;-)

**Comment by kakenbok** [comment]
ich bin mit dieser lösung nicht zufrieden. wir möchten eine backendseitige validierung, weil dort die letzte instanz ist, die integrität unserer daten zu sichern.

**Comment by kakenbok** [comment]
der "böse" commit ist https://github.com/AfeefaDe/afeefa-backend-api/commit/87ecc23f8de3eb4d0089093743b714cb6965915e

bitte eine andere lösung schaffen.

**Comment by stevereinke** [comment]
ich habe die migration und das schema nun wieder glatt gezogen und in den models validierung nach gesundem menschenverstand in anlehnung an den mysql datentyp implementiert

**Comment by kakenbok** [comment]
ich komme noch nicht zu einer technischen begutachtung. muss offen bleiben.
