### ISSUE TITLE
Validierung in contactInfos funktioniert nicht

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#306]
Seit dem wir die Formulare der contactInfo in eine eigene Komponente ausgelagert haben, funktioniert VeeValidate's `validateAll()` nicht mehr. Es wird als beim Speichern keine Fehlermeldung geworfen.

**Comment by friedrichweise** [comment]
Durchaus noch relevant. Es kann so die Validierung ausgehebelt werden.

**Comment by friedrichweise** [comment]
__Vermutung:__ Es liegt nicht an der Tab-Implementierung (mit `v-show`) sondern an der Auslagerung in eine eigene Komponente.

**Comment by friedrichweise** [comment]
__Mögliche Lösungen__
* EventBus, validateAll wird in jedem Child Komponente aufgerufen: https://gist.github.com/sproogen/147d75db261505e8a558a7fd11a20551
* der Wechsel der Tabs fordert die Validierung

**Comment by kakenbok** [comment]
festellung: validierung url api-seitig fehlt

**Comment by friedrichweise** [comment]
Weitere Feststellung: Mailadresse wird api-seitig auch nicht validiert.

**Comment by friedrichweise** [comment]
Ich werde mit diesem Ticket auch die neuste Version von vee-validate installieren. Aufgrund von https://github.com/baianat/vee-validate/issues/863 warte ich noch auf das nächste Release.

**Comment by friedrichweise** [comment]
`TypeError: Cannot read property 'srcElement' of null` ist der aktuellen Version von vee-validate geschuldet.

**Comment by stevereinke** [comment]
ist das erledigt? wer testet das?

**Comment by kakenbok** [comment]
bitte testen
