### ISSUE TITLE
Suche intelligenter machen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#307]
auf Anregung von Hagen, haben Felix, Steve und Anna sich auf folgende Suchlogik geeinigt:

- es gibt nur ein suchfeld
- es gibt eine dropdown-liste, in der ich zwischen [Alles | Titel | Kurzbeschreibung | Adresse | ...] wählen kann
  - = **Suchmenge**,  also Menge der Attribute, in denen gesucht werden soll
  - in der Auswahlliste sind also einzelne attribute, aber auch sammelbegriffe wie "Alles" und "Adresse"
  - die UI macht sich über sammelbegriffe keine platte, sondern jagt einfach eine suche in dieser "suchmenge" los
- mehrere leerzeichen-getrennte suchbegriffe im suchfeld werden UND verknüpft
- die B.API sucht dann nach allen Einträgen, in denen beide suchbegriffe innerhalb der Suchmenge vorkommen

Beispiele:

| _nossen kinder_ | in ALLES
`entries/?filter[any]=nossen+kinder`
  - "Kindergarten" (title) in Nossen (city)
  - "Nossener Bücherecke" (title) die "viele Angebote für Kinder" hat (shortdescription)
  - nossen und kinder müssen beide im eintrag vorkommen, allerdings kann es verteilt in irgendeinem attribut des eintrags sein

| _nossen kinder_ | in TITEL
`entries/?filter[title]=nossen+filter`
  - "Nossener Kindercafe" (title)
  - "Beratung für Mütter und Kinder in Nossen Nord" (title)

| _"nossen kinder"_ | in TITEL
`entries/?filter[title]="nossen+filter"`
  - "Nossen Kinderfest" (title)

Formal ist das dann folgende Definition:
x y ≔ { e | (x ∈ A1 ∨ … ∨ x ∈ An ) ∧ (y ∈ A1 ∨ … ∨ y ∈ An) }
mit A als Menge der Attribute, in denen gesucht wird

**Comment by HagenBeelitz** [comment]
siehe #289

**Comment by friedrichweise** [comment]
😍  Diese formale Definition 😍

**Comment by felixkamille** [comment]
na ja, geht so wa. hinkt bissl die Mengenschreibweise, denk ich.

**Comment by felixkamille** [comment]
läuft.
