### ISSUE TITLE
Add fax attribute to contact infos

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#308]

**Comment by kakenbok** [comment]
klappt zwar, aber die input-felder haben kein maxlength. deshalb kann ich unendlich lange faxnummern eingeben.

**Comment by friedrichweise** [comment]
Finde ich nicht schlimm. Auch Telefonnummer wird nicht weiter validiert.

**Comment by kakenbok** [comment]
fax ist raus, gibts nicht mehr. wird nicht mehr unterstützt.
