### ISSUE TITLE
Als Nutzer:in möchte ich aktive und inaktive Orgas und Events angezeigt bekommen.

### ISSUE THREAD

**Issue by HagenBeelitz** [AfeefaDe/afeefa-backend-ui#310]
Add filter bar (like todo) to filter for active and inactive entries in orga and event list. Maybe additionally add past and upcoming events for event filter (to prevent the subsection past events).

**Comment by friedrichweise** [comment]
Technisch kein großes Ding. Trotzdem würde ich gerne erst Rücksprache mit den Redakteuren halten.

**Comment by kakenbok** [comment]
was sagen diese denn?
