### ISSUE TITLE
Als Redakteur möchte ich für einen Eintrag festlegen können, ob er sich explizit an eine bestimmte Zielgruppe wendet, z.B. Kinder, Frauen, Männer, Refugees etc.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#311]
das Attribut `forChildren` kann dann darin integriert werden. die suchanfrage hierfür ist bereits vorbereitet:

`afeefa.de/search/group:women`

ins frontend sollte das so kommen:
```
{
	...
	group: {
		women: true,
		children: false,
		refugees: true
		...
	}
	...
}
```

**Comment by friedrichweise** [comment]
Gibt es eine vordefinierte Liste an "Zielgruppen" ? Oder kann der Redakteur selbst welche definieren ? @felixkamille

**Comment by friedrichweise** [comment]
Vordefiniert.
