### ISSUE TITLE
Als Redakteur möchte ich bei einem Eintrag, der mit "Unterstützung benötigt" markiert ist, eine zusätzliche Beschreibung über Details zu benötigten Unterstützung angeben können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#312]
Feld ist bereits im Eintragsformular vorbereitet:
https://afeefa.de/add

**Comment by friedrichweise** [comment]
- [ ] BackendUI Formular und Attribut (optional, max 350 Zeichen)
- [ ] BackendAPI Attribut
- [ ] Ausgabe im Frontend

**Comment by felixkamille** [comment]
Umsetzing im FE wie folgt:
- Anzeige in Detailansicht eines Eintrags
- Anzeige als Snippet innerhalb der "Unterstützung gesucht"-Suche
- Anzeige als Snippet bei der Volltextsuche, falls Treffer
