### ISSUE TITLE
Als Redakteur möchte ich mehrere Email Adressen für einen Eintrag angeben können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#316]
das einfachste wäre wohl einfach kommegetrennt; Problem könnte dann aber die native Validierung sein > ist es eine native Validierung?

**Comment by friedrichweise** [comment]
* Multiselect in Backend UI einbauen
* Frontend auf Änderungen vorbereiten

**Comment by friedrichweise** [comment]
Mehrere `contactInfo` sind bereits möglich. Bei Bedarf bauen wir die UI.
