### ISSUE TITLE
bautzen daten importieren

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#321]
bautzen daten inkl übersetzungen nochmal auf LIVE importieren

area setzen: `bautzen`
user besteht bereits: projektleitung@hor-bautzen.de

für den import der eintragsdaten existiert ein ruby import script. für den import von übersetzungen existiert noch kein workflow.

aktuelle liste mit daten bei Felix erfragen

**Comment by stevereinke** [comment]
so, import ist durch, behandelt nun auch doppelte titel und setzt die unterkategorie korrekt.
schaust du nochmal drüber?

**Comment by felixkamille** [comment]
tip top!
