### ISSUE TITLE
Als Redakteur möchte ich TAGS über ein chosen Feld eingeben können um mich an einer vorgegebenen Liste von Tags orientieren zu können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#323]
kontinuierliche Tagsammlung unter https://github.com/AfeefaDe/afeefa-neos/issues/2279

**Comment by friedrichweise** [comment]
Sollen nur diese drei zur Auswahl stehen ? Oder sollen Redakteure auch neue Tags eintragen können (sprich Freitext) ?

**Comment by kakenbok** [comment]
klappt, nur vorgegebene tags stehen zur auswahl. tags hinzugefügt und tags entfernt. topp.
