### ISSUE TITLE
Problemfälle des Backend-UI-Cache überdenken

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#327]
Einige der offenen Bugs hängen mit dem Caching-System der Backend-UI zusammen:
* #264: Bug: wenn entry mit parent gelöscht wird, kann dieses noch über den Parent gefunden werden
* #265: Bug: wenn ein Eintrag gelöscht wird, kann dieser noch über die Suche gefunden werden
* `wenn man auf bearbeiten drückt sieht man alle daten` (aus Slack #bugs)

Wir sollten mal genau definieren, wann welche Daten nach welchen Aktionen (Löschen, Speichern...) neu geladen werden müssen.

**Comment by kakenbok** [comment]
alle punkte sind mit backend2 behoben
