### ISSUE TITLE
forChildren attribut kann raus

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#329]
das wird langfristig durch eine komplexere zielgruppenauswahl ersetzt. einträge, die dieses attribut gesetzt hatten, haben mittlerweile den tag 'youth', der bis zur zielgruppenauswahl diesen aspekt erstmal überbrückt.

das Attribut kann also überall entfernt werden.

**Comment by friedrichweise** [comment]
Was besteht mit den existierenden Datenbankeinträgen ?
