### ISSUE TITLE
Ich möchte immer wissen, wo ich mich befinde.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#33]
- [x] Menü zeigt alle möglichen Seiten: todos, orgas, suche, events, dashboard, add event/orga
- [x] Breadcrumb in oberer Headerline on top of page
- [x] Headline auf Eintragsseiten View/Edit

**Comment by kakenbok** [comment]
* Title
* Breadcrumb
* Überschrift h1 'Organisationen'
* Überschrift h2 'Orga anzeigen/ändern/hinzufügen'

**Comment by HagenBeelitz** [comment]
- [ ] Dashboard < entfernen
