### ISSUE TITLE
Als Redakteur möchte ich vergangene Events nicht per default suchen können

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#330]
Zitat Anna

**Comment by kakenbok** [comment]
warum werden alte events überhaupt noch angezeigt bzw. gespeichert?

**Comment by kakenbok** [comment]
die suche liefert noch immer vergangene events aus, zur info.

**Comment by kakenbok** [comment]
in den listen kann man jetzt nach aktiv/nicht aktiv filtern
