### ISSUE TITLE
Kontakt Tab wird nicht angezeigt

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#333]
scheinbar nur hier beim Eintrag des Sächs. Flüchtlingsrats: https://backend.afeefa.de/orgas/1845?tab=contactTab

**Comment by friedrichweise** [comment]
Das liegt an dem Sprachcode `tm`. Dieser wird nicht erkannt. Ich habe die Sprache mal händisch entfernt.
