### ISSUE TITLE
categories mit area(s) verknüpfen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#336]
- datenstruktur varianten
  - 1:n = eine category sollte mehreren areas zuordnungsbar sein, da viele categories in mehreren areas genutzt werden.
  - 1:1 = jede kategorie explizit pro area anlegen, auch wenn es die kategorie mehrmals gibt; grund: es wird unterkategorien geben, die in unterschiedlichen areas untersch. parents haben

- die B.API sollte die categories abhängig von der area des users ausgeben
- die B.UI sollte dementsprechend nur relevante categories anzeigen

Beispiele zum Umsetzen:

`bautzen`
- 'general` > 'swimming` (nur swimming ist neu und nur für bautzen)

`leipzig`
- `Ehrenamt` > `Ehrenamtskoordination`
- `Ehrenamt` > `Patenschaften`

**Comment by stevereinke** [comment]
Kategorie bekommt eine Verknüpfungstabelle, in welcher die area und die Elternbeziehung ausgelagert wird. -> category_configurations
categories 1:n category_configurations

**Comment by friedrichweise** [comment]
Als Hinweis: Es existiert noch das Ticket #64. Wird möglicherweise hier mit behandelt.

**Comment by stevereinke** [comment]
ACHTUNG: #64 wird hier nicht behandelt. Das lösen wir mit dem Ausbau des json-api-resources gem separat

**Comment by stevereinke** [comment]
api implementierung sollte soweit passen. wenn du die area auch ausgegeben haben willst, dann gib nochmal bescheid.

**Comment by felixkamille** [comment]
categories müssen auch noch über die FAPI raus. ich glaube, da gibt es noch gar keine route.

**Comment by stevereinke** [comment]
frontend api erledigt mit #383

**Comment by felixkamille** [comment]
läuft.
