### ISSUE TITLE
entry mit user verknüpfen (creator, editor)

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#337]
Datenmodell A:
- jeder entry bekommt einen `creator` beim erstellen
- entry bekommt einen `last_editor` nach dem bearbeiten

Datenmodell B:
- pro interaktion, z.B. entry erstellen oder bearbeiten, wird eine activity in einer extra tabelle geloggt, z.B...  
`user_id | entry_id | activity_type | timestamp`  
`7 | 2372 | update | 2017-09-02 11:55`  
`5 | 2372 | create | 2017-08-22 17:02`
- die logging tabelle kann über die zeit mit anderen user activities erweitert werden, z.B. "annotation angelegt", "eintrag veröffentlicht"

**Comment by stevereinke** [comment]
empfohlenes gem: public_activity

**Comment by kakenbok** [comment]
früheres ticket: #176

**Comment by stevereinke** [comment]
Hat das schonmal jemand getestet?
