### ISSUE TITLE
Vorschaulink an area anpassen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#338]
leipzig > leipzig.afeefa.de
bautzen > bautzen.afeefa.de

**Comment by friedrichweise** [comment]
Live und Dev-Betrieb beachten.

**Comment by friedrichweise** [comment]
Für den Dev Betrieb gibt es gar keine entsprechenden Domains (leipzig.dev.afeefa.de, bautzen.dev.afeefa.de)

**Comment by kakenbok** [comment]
für dev nach konfigurierbarer lösung suchen. zb. alert 'der link auf afeefa-leipzig würde jetzt geöffnet werden'
