### ISSUE TITLE
certified Attribut bei area != dresden raus

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#339]
Siegel vom Flüchtlingsrat brauchen wir außerhalb Dresdens nicht

**Comment by friedrichweise** [comment]
Bräuchte zusätzlich API Support. Quick Fix: in ui ausblenden.

**Comment by kakenbok** [comment]
getestet mit dd und le, dd certified im UI, le nicht certified im UI, api nicht getestet

**Comment by stevereinke** [comment]
soll die api hierzu noch angepasst werden?

**Comment by kakenbok** [comment]
nö
