### ISSUE TITLE
Als Redakteur möchte ich sehen, zu welcher Organisation ein Nutzer gehört, der einen Eintrag geändert oder erstellt hat.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#340]
Beispiele:
- user.organization = `Bürgerstiftung Leipzig`
- user.organization = `Stadt Leipzig, Referat Migration`

**Comment by stevereinke** [comment]
Gibt es dazu ein Konzept bzw. eine konkrete Anforderung?

**Comment by felixkamille** [comment]
Hier bitte auch noch die Orga ausgeben:
![image](https://user-images.githubusercontent.com/1052429/33145858-47e37606-cfc2-11e7-89ab-ee0ebedf767c.png)
![image](https://user-images.githubusercontent.com/1052429/33145889-60223982-cfc2-11e7-8ad6-8bbcbcf0e055.png)

**Comment by felixkamille** [comment]
duplicate with #400
