### ISSUE TITLE
alle system-generierten Annotations aus der Filter-Dropdown-Liste raus

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#342]
alle diese TODOs sind abgearbeitet und können im Filter ausgeblendet werden. nur "Kurzbeschreibung fehlt" kann noch bleiben.

**Comment by friedrichweise** [comment]
Vorschlag: AnnotationCategory aus DB löschen.

**Comment by friedrichweise** [comment]
Nur leere löschen.

**Comment by kakenbok** [comment]
ich sehe einige kategorien in der tabelle annotation_categories.

`select * from annotation_categories ac left join annotations a on ac.id = a.annotation_category_id
where a.id is null`

=> 

UnknownTable
---
| id | title | generated_by_system | created_at | updated_at | id | annotation_category_id | entry_type | entry_id | detail | 
| -: | - | -: | - | - | -: | -: | - | -: | - | 
| 29 | Titel ist zu lang | 1 | 2017-06-21 17:16:30 | 2017-06-21 17:16:30 | \N | \N | \N | \N | \N | 
| 30 | Titel ist bereits vergeben | 1 | 2017-06-21 17:16:30 | 2017-06-21 17:16:30 | \N | \N | \N | \N | \N | 
| 31 | Kurzbeschreibung ist zu lang | 1 | 2017-06-21 17:16:30 | 2017-06-21 17:16:30 | \N | \N | \N | \N | \N | 
| 33 | Hauptkategorie fehlt | 1 | 2017-06-21 17:16:30 | 2017-06-21 17:16:30 | \N | \N | \N | \N | \N | 
| 34 | Unterkategorie passt nicht zur Hauptkategorie | 1 | 2017-06-21 17:16:30 | 2017-06-21 17:16:30 | \N | \N | \N | \N | \N | 
| 35 | Start-Datum fehlt | 1 | 2017-06-21 17:16:30 | 2017-06-21 17:16:30 | \N | \N | \N | \N | \N | 
| 37 | Ort | 0 | 2017-06-21 17:16:31 | 2017-06-21 17:16:31 | \N | \N | \N | \N | \N | 
| 39 | Bild | 0 | 2017-06-21 17:16:31 | 2017-06-21 17:16:31 | \N | \N | \N | \N | \N | 
| 40 | Kategorie | 0 | 2017-06-21 17:16:31 | 2017-06-21 17:16:31 | \N | \N | \N | \N | \N | 
| 41 | Zugehörigkeit | 0 | 2017-06-21 17:16:31 | 2017-06-21 17:16:31 | \N | \N | \N | \N | \N | 
| 45 | EXTERNE EINTRAGUNG | 0 | 2017-09-07 22:01:57 | 2017-09-07 22:02:00 | \N | \N | \N | \N | \N |

**Comment by kakenbok** [comment]
reopen, weil jetzt unklar, was der fix ist.

**Comment by stevereinke** [comment]
was ist hier der gewünschte zielzustand?

**Comment by friedrichweise** [comment]
@felixkamille

**Comment by kakenbok** [comment]
ist das noch relevant?

**Comment by kakenbok** [comment]
ist das  noch relevant?
