### ISSUE TITLE
redirect nach login funzt nicht mehr

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#345]
ist schade, da wir das gut für direktlinks zum bearbeiten gebrauchen können, zb:
- aus dem frontend heraus (rechtsklick auf updated time stamp)
- aus email-benachrichtigung über neuen eintrag heraus

**Comment by friedrichweise** [comment]
Kann ich nicht reproduzieren. Unter welchen Umständen trifft das Problem denn auf ?

**Comment by friedrichweise** [comment]
Nicht reproduzierbar.
