### ISSUE TITLE
Als Redakteur möchte ich eine visuelle Rückmeldung erhalten, über welche Einträge und Attribute meine Suche durchgeführt wird.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#35]

**Comment by kakenbok** [comment]
Suchprozess für Nutzer transparent: Was passiert im Hintergrund? Was wird durchsucht? ...

**Comment by friedrichweise** [comment]
The label of the input is **title**. That should be enough. 
Story should be closed.

**Comment by kakenbok** [comment]
gonna add this question to the next user testing. for now closing this.
