### ISSUE TITLE
vee-validate errors

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#350]
nach dem anlegen eines neuen events

**Comment by kakenbok** [comment]
![Screenshot_2017-10-02_12-57-56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581edee88223d70e000991a1/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1c36417773e79569c7a22c8b67ff2172d43434d0eee1e020a17b8eb8339a3be3d258f5f0eb9d9685e26c56f17a4b8824bb906b928dd5d99a4fedb1294b7607caddecd5d340c041f83fe5835a6904fc951f342e14452b65e.png)

**Comment by friedrichweise** [comment]
Fixed in #306

**Comment by stevereinke** [comment]
wer testet das?
