### ISSUE TITLE
Als Redakteur möchte ich einem Eintrag ein Datum auf einfache und übersichtliche Weise zuweisen können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#36]
- [x] input in textarea austauschen

**Comment by kakenbok** [comment]
*  Kalender Widget (mobile first)
* aktuelles Datum und Zeit vorausgewählt
* Scrollen ändert Datum und Zeit
* Endzeit auswählbar
* Endzeit darf nicht vor Anfangszeit liegen
* usw

**Comment by kakenbok** [comment]
for desktops use https://chmln.github.io/flatpickr/

**Comment by kakenbok** [comment]
Frage: Linebreaks erlauben oder nicht?
Frage: Länge der Beschreibung?

**Comment by felixkamille** [comment]
date/ time/ datetime auf native unterstützung testen: http://html5-webdesign.de/input.html

**Comment by friedrichweise** [comment]
- [ ] The selected date should be displayed in a black font color

**Comment by kakenbok** [comment]
There is no close button option. if people encounter problems -> raise a bug.
