### ISSUE TITLE
Ich möchte eine Kontaktperson per Click/Tap direkt kontaktieren können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#37]
- [x] Mail
- [ ] Phone

**Comment by kakenbok** [comment]
Sollte nochmal mit dem Backend abgesprochen werden. Es dürfen zum Beispiel keine `/` vorkommen:
https://css-tricks.com/the-current-state-of-telephone-links/

**Comment by kakenbok** [comment]
Aus meiner Sicht klares B-Feature und geringe Prio, insbesondere da Backend wahrscheinlich hauptsächlich im Desktop benutzt.

**Comment by kakenbok** [comment]
(Mail oder Phone)

**Comment by kakenbok** [comment]
we decided not to implement phone calls. emails are working properly.
