### ISSUE TITLE
Abhängigkeiten aktualisieren

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#370]
* vue, vue-router, vuex, vue-template-compiler: 178d07c
* vue-multiselect: 9133a35
* materialize-css: 6162b64

**Comment by stevereinke** [comment]
wer testet das?

**Comment by friedrichweise** [comment]
Habs zugewiesen.

**Comment by kakenbok** [comment]
offenbar ich

**Comment by kakenbok** [comment]
funkt
