### ISSUE TITLE
Prototyp Ressourcen-Tool

### ISSUE THREAD

**Issue by stevereinke** [AfeefaDe/afeefa-backend-ui#377]

**Comment by friedrichweise** [comment]
### Todo Backend-UI
- [ ] EntryList Komponente für Ausgabe verwenden
- [ ] Ausblenden des Resource-Tabs, wenn keine vorhanden sind

**Comment by stevereinke** [comment]
was passiert mit diesem ticket? noch relevant?

**Comment by kakenbok** [comment]
ich legs mal ad akta, wir können es ja später aus den tiefen hervorholen.
