### ISSUE TITLE
neue Frontend-Entry-URL mit slug für backend preview button nutzen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#379]
da es jetzt speaking URLs im frontend gibt, werden die alten URLs vom frontend nicht mehr gefunden, zb `/project/2345`.

dass da kein fallback drin ist, ist absicht, wegen duplicate content für google. korrekterweise müsste man ja eine 404 oder ein redirect für die alten URLs ausgeben, aber das ist ja gerade zu kompliziert für unser liebes kleines frontend.

der frontend frisst aber dennoch jegliche URL, hauptsache sie enthält `id-` also das minus muss sein, aber alles dahinter ist egal und es wird immer die ID ermittelt, zb...

https://afeefa.de/project/4265-textilkultur-und-interart

https://afeefa.de/project/4265-textille

https://afeefa.de/project/4265-kackbratzenscheiße

**Comment by friedrichweise** [comment]
Duplikat von #219
