### ISSUE TITLE
Als Redakteur möchte ich einen Eintrag löschen können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#38]
- [x] style delete button
- [ ] Keine Einträge mit Kindern löschen (Kinder = Event, Suborga) sondern erst alle Kinder löschen
  Hinweis statt Button: "es müssen erst alle kinder gelöscht werden"
- [ ] Alle Relations sind gelöscht
  - delete unvalidated entries
- [ ] Confirm dialog (ja/nein)
- [ ] Zurück zur letzten Liste navigieren, von wo aus der Eintrag aufgerufen wurde
- [ ] Response: Eintrag wurde gelöscht

**Comment by stevereinke** [comment]
Sollen Daten jemals tatsächlich gelöscht werden?
 * Datenschutz und so
Was passiert mit verknüpften Daten beim Löschen?
  * verschieben oder löschen?
 * automatisiert oder entscheidet der Nutzer darüber?

**Comment by stevereinke** [comment]
TODOs im Code abarbeiten, soft destroyable für alle Models

**Comment by felixkamille** [comment]
löschen von einträgen mit kindern verbieten und hinweis geben:
> es müssen erst alle kinder gelöscht werden

**Comment by friedrichweise** [comment]
- [ ] Response
- [ ] delete unvalidated entries

**Comment by kakenbok** [comment]
Problem aktuell mit Softdelete: Daten werden validiert, was beim Löschen nicht passieren sollte.

**Comment by felixkamille** [comment]
Grund: Backup der Daten, falls mal etwas versehentlich gelöscht wurde. Wenn das so kompliziert ist, können wir mE das softdelete über eine Zustandsänderung auch weglassen und die Daten tatsächlich löschen, also aus der Persistenz entfernen. Gefahr: ein einzelner Eintrag könnte verloren gehen, der in seinem Informationsgehalt aber nicht so groß ist und in fast allen Fällen manuell durch einen Redakteur gut reproduzierbar sein sollte.

**Comment by kakenbok** [comment]
super! das macht alles einfacher und schneller.
