### ISSUE TITLE
"Übersetzungen" Modul raus aus BE

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#380]

**Comment by felixkamille** [comment]
zumindest brauchen wir keinen Button mehr für "Übersetzungen auslösen". Auf die Seite an sich könnte aber irgendeine Übersetzungsstatistik zur Abdeckung, beauftragten Übersetzungen etc.

**Comment by kakenbok** [comment]
ist raus, bitte abnehmen

**Comment by felixkamille** [comment]
Ist raus :)
