### ISSUE TITLE
Bautzen/Leipzig Entries relate to Dresden-Categories

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#381]

**Comment by stevereinke** [comment]
wie sieht hier die lösung aus? neue kategorien für le/bz anelgen? und dann die entries verknüpfen? das wäre so ne art migration, könnte man auch direkt auf der db machen...

**Comment by felixkamille** [comment]
wurde bereits gelöst. es gibt für BZ/LE extra kategorien, also keine relation bzw. wiederverwendung.
