### ISSUE TITLE
area specific categories for LEIPZIG

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#387]
die FAPI gibt nun die kategorien der jeweiligen area aus und das frontend empfängt sie ordnungsgemäß > #383

wenn jetzt leipzig kategorien angelegt werden, muss auch noch für jede kategorie folgendes erledigt werden:

Afeefa frontend:
- symbol + farbe über frontend css definieren
- key für diese kategorie in phraseapp anlegen um deutsche und andere übersetzungen zu erhalten (labels)
- user entry form mit entsprechender kategorie in der dropdown ausstatten (momentan hard coded in html template des entry forms)

backend UI:
- ebenfalls area-abhängig die categories laden (geht das schon?)
- übersetzung für category im BUI eigenen language handling anlegen

**Comment by friedrichweise** [comment]
Die Ausgabe läuft lediglich über die Frontend-API?
Wenn ich das jetzt ins Backend einbaue, würde ich das natürlich lieber als Backend-API Ressource bekommen. Via Frontend-API geht natürlich auch, ist aber ein bisschen Gefrickel.

**Comment by friedrichweise** [comment]
- [ ] Ausblenden des Select's für leere Unterkategorien.

**Comment by friedrichweise** [comment]
Kategorien werden bereits geladen. Die API liefert anhand des `Areas` des Nutzers die entsprechenden Kategorien aus.

**Comment by felixkamille** [comment]
das ticket hier ist sehr allgemein. wir haben die einzelnen aspekte diskutiert und aufgaben daraus abgeleitet. ich mach zu.
