### ISSUE TITLE
Parallele Prozesse für Unicorn aktivieren

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#391]
wir haben festgestellt, dass unsere request immer nur subsequent abgearbeitet werden. wir möchten das gerne parallelisieren und hoffen auf einen performance-boost dadurch!

**Comment by stevereinke** [comment]
aktueller Stand:
dev jeweils ein Prozess für backend-api und frontend-api
live backend-api 2 prozesse, frontend-api 4 prozesse

**Comment by kakenbok** [comment]
wie kann ich das testen?

**Comment by stevereinke** [comment]
Schauen, wie viele Prozesse auf dem System laufen. Es sollte je 1 master und x worker geben.
