### ISSUE TITLE
Als Redakteur möchte ich lange Dropdown-Listen immer alphabetisch sortiert vorfinden, damit ich schneller Einträge finden kann.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#40]
- [ ] Events and Todos not affected

**Comment by kakenbok** [comment]
Liste standardmäßig nach A-Z sortieren (zB Parent-Orga Dropdown)

**Comment by kakenbok** [comment]
hier gehts um das orga-select

**Comment by friedrichweise** [comment]
- [ ] Sort created entries by ember

**Comment by kakenbok** [comment]
Related to #87 (non trimmed titles)

**Comment by kakenbok** [comment]
danke steve für serverseitiges trim. getestet mit full dump von neos. klappt super, groß- und kleinschreibung wird ignoriert. leerzeichen am anfang/ende sind weg.

feststellung: wir haben drei sonderfälle:

1. "LOUISE" Haus für Kinder, Jugendliche
2. *sowieso* Kultur Beratung Bildung
...
3. „Deutsch sofort“ im DPFA

diese werden wie aufgelistet vor oder nach allen anderen einträgen gelistet.
