### ISSUE TITLE
Textarea für Annotationtag

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#404]
Redakteure möchten mehr als eine Zeile eintragen.

**Comment by kakenbok** [comment]
super klappt!

**Comment by kakenbok** [comment]
@felixkamille bitte abnehmen

**Comment by felixkamille** [comment]
Geht wie Butter. I like it!

Letzte Anmerkung: einer system annotation kann man keine Details hinzufügen. Ist wahrscheinlich Absicht? Ist wohl auch gut so. Dachte nur immer, das könne man und würde ja auch Sinn machen.
