### ISSUE TITLE
phraseapp eingaben sind nicht on demand im FE sichtbar

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#405]
englische + arabische Eintragungen von Anna am 29.11. zum event mit ID=1909 wurden nicht direkt im frontend angezeigt. erst der cronjob über nacht brachte sie ans tageslicht.

**Comment by kakenbok** [comment]
im live.phraseapp war kein webhook eingetragen, warum auch immer.

außerdem haben wir den server neu gestartet.
