### ISSUE TITLE
Problem bei der Servermigration

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#407]
Unsere Backend-API kommt nicht mit der aktuellen MySQL Version klar. Das hindert Felix gerade an der Migration des Servers:

```
I, [2017-11-26T13:10:36.531374 #19146]  INFO -- : [34a5b98f-c6c5-4f02-90bf-58059a352407] Completed 200 OK in 3436ms (Views: 329.5ms | ActiveRecord: 52.1ms)
I, [2017-11-26T13:10:36.532823 #19146]  INFO -- : [48453257-d162-445e-87fe-183c38020018] Started GET "/api/v1/todos" for 127.0.0.1 at 2017-11-26 13:10:36 +0100
I, [2017-11-26T13:10:36.533351 #19146]  INFO -- : [48453257-d162-445e-87fe-183c38020018] Processing by Api::V1::TodosController#index as JSON
D, [2017-11-26T13:10:36.534459 #19146] DEBUG -- : [48453257-d162-445e-87fe-183c38020018]   ESC[1mESC[36mUser Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT  `users`.* FROM `users` WHERE `users`.`uid` = 'friedrich@weise.io' LIMIT 1ESC[0m
D, [2017-11-26T13:10:36.536771 #19146] DEBUG -- : [48453257-d162-445e-87fe-183c38020018]   ESC[1mESC[36mAnnotation Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT `annotations`.* FROM `annotations` LEFT JOIN orgas ON orgas.id = annotations.entry_id AND entry_type = 'Orga' LEFT JOIN events ON events.id = annotations.entry_id AND entry_type = 'Event' WHERE (orgas.area = 'dresden' OR events.area = 'dresden') GROUP BY `annotations`.`entry_id`, `annotations`.`entry_type`ESC[0m
I, [2017-11-26T13:10:36.537004 #19146]  INFO -- : [48453257-d162-445e-87fe-183c38020018] Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.2ms)
F, [2017-11-26T13:10:36.537876 #19146] FATAL -- : [48453257-d162-445e-87fe-183c38020018]   
F, [2017-11-26T13:10:36.537918 #19146] FATAL -- : [48453257-d162-445e-87fe-183c38020018] ActiveRecord::StatementInvalid (Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'afeefa_live.annotations.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: SELECT `annotations`.* FROM `annotations` LEFT JOIN orgas ON orgas.id = annotations.entry_id AND entry_type = 'Orga' LEFT JOIN events ON events.id = annotations.entry_id AND entry_type = 'Event' WHERE (orgas.area = 'dresden' OR events.area = 'dresden') GROUP BY `annotations`.`entry_id`, `annotations`.`entry_type`):
F, [2017-11-26T13:10:36.537952 #19146] FATAL -- : [48453257-d162-445e-87fe-183c38020018]   
```

**Comment by friedrichweise** [comment]
Zum testen einfach `/etc/hosts` anpassen:
`178.238.229.190 afeefa.de *.afeefa.de api.afeefa.de www.afeefa.de api.backend.afeefa.de backend.afeefa.de`

**Comment by stevereinke** [comment]
Das ist doch das bereitd im tech talk besprochene Problem mit dem sql_mode. 
Wenn der korrekt gesetzt ist, dann geht das. Wir wollten die API langfristig eh umbauen, da würde ich jetzt kurzfristig nur ungern an der API basteln. Oder jemand anderes schaut sich das mal an. Eigentlich müssen da nur mal die Felder aus dem select auch in das group by, so verstehe ich die Meldung zumindest.

**Comment by friedrichweise** [comment]
@Stunkymonkey irgendwelche Neuigkeiten?

**Comment by Stunkymonkey** [comment]
hab noch keite zeit gefunden 🙈

**Comment by Stunkymonkey** [comment]
ich hab noch nicht ganz verstanden was dieser mysql mode macht, aber gut
die todos funktionieren

dann wäre da noch, dass das Frontend und Facebook nicht miteinander kommunizieren

wobei das vielleicht auch an den cors headern liegen kann

**Comment by Stunkymonkey** [comment]
beim backend merke ich gerade, dass die console viele fehler bringt. Vielleicht schaut sich das besser nochmal jemand an, da ich mit den Fehlermeldungen gar nichts anfangen kann.

**Comment by Stunkymonkey** [comment]
ich bekomme auf der console beim frontend immer noch folgenden Fehler:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://backend.afeefa.de/api/v1/facebook_events?token=zP4uja4yFmnPWZeCVsLU. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
ich habe dann die CORS-Header für https://backend.afeefa.de hinzugefügt. Allerdings funktioniert es hier weiterhin nicht.
Jemand ne Idee?

**Comment by friedrichweise** [comment]
Request Headers im Live System:
```
GET /api/v1/facebook_events?token=zP4uja4yFmnPWZeCVsLU HTTP/1.1
Host: backend.afeefa.de
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
Origin: https://afeefa.de
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
DNT: 1
Referer: https://afeefa.de/
Accept-Encoding: gzip, deflate, br
Accept-Language: en,de;q=0.9,en-US;q=0.8,sw;q=0.7
If-None-Match: W/"621f8f6630e7569dcd5da9be55e4e7fb"
?
```
Request Header auf den neuen Server:

```
:authority:backend.afeefa.de
:method:GET
:path:/api/v1/facebook_events?token=zP4uja4yFmnPWZeCVsLU
:scheme:https
accept:application/json, text/javascript, */*; q=0.01
accept-encoding:gzip, deflate, br
accept-language:en,de;q=0.9,en-US;q=0.8,sw;q=0.7
dnt:1
if-none-match:W/"621f8f6630e7569dcd5da9be55e4e7fb"
origin:https://www.afeefa.de
referer:https://www.afeefa.de/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```

**Comment by friedrichweise** [comment]
Nach meinem Verständnis werden die Header vom Rails Server gesetzt. Die Implementierung liegt in <a href="https://github.com/AfeefaDe/afeefa-backend-api/blob/dev/app/controllers/concerns/cors.rb">cors.rb</a>. Kannst du das bestätigen, @stevereinke ?

**Comment by Stunkymonkey** [comment]
> Request Headers im Live System:
> Request Header auf den neuen Server:

also mag sein, dass ich blind bin, aber ich seh als unterschied nur `Connection: keep-alive`

**Comment by stevereinke** [comment]
Origin: https://afeefa.de muss im Request vorhanden sein, damit der CORS-Header korrekt gesetzt wird. 
Nun sehe ich im neuen Request: origin:https://www.afeefa.de, möglicherweise ist das case-sensitiv?
Das müsste man prüfen... vermutlkich direkt mal im Rails debuggen...

**Comment by stevereinke** [comment]
ach ne, ich hab grad folgendes im code gefunden:

            http://localhost:3000
            http://localhost:3002
            https://dev.afeefa.de
            https://afeefa.de

also ist ww.afeefa.de nichtzulässig laut unserer liste

**Comment by stevereinke** [comment]
das ist jedoch konfigurierbar via Settings.api.allowed_cors_origins

**Comment by Stunkymonkey** [comment]
in der datei: `afeefa-backend-api/current/app/controllers/concerns/cors.rb`?
oder wo genau muss ich das angeben wenn du  "Settings.api.allowed_cors_origins" meinst?

**Comment by Stunkymonkey** [comment]
@stevereinke ???

**Comment by friedrichweise** [comment]
Nein. Dafür gibt es lokale `settings.yml` Dateien. Ein Beispiel findest du hier:
`/home/afeefa/rails/afeefa-backend-api/current/config/settings.local.yml`

**Comment by Stunkymonkey** [comment]
ein neuer Fehler in der Console:
`AUTH: No auth user found. Load credentials from local storage.`
muss ich da noch was importieren aus der alten installation?

**Comment by friedrichweise** [comment]
Der Fehler kommt vom Session Management unseres JavaScript Clients. Das klingt aber erstmal gut. Kannst du mir nochmal die Serveradresse zum Testen zusenden?

**Comment by friedrichweise** [comment]
Damit läuft das Backend soweit.

**Comment by kakenbok** [comment]
:thumbsup:
