### ISSUE TITLE
Abbrechen-Dialog wird ohne Änderungen angezeigt

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#409]
Bei folgenden Vergleichen (keine Änderungen durch User) wird der Dialog gezeigt (Event editieren, dann gleich wieder schließen):

**Comment by friedrichweise** [comment]
<img width="1255" alt="screen shot 2017-12-13 at 16 46 56" src="https://user-images.githubusercontent.com/7392490/33947692-5f7e6014-e025-11e7-849b-7d652d8778bf.png">

(DatePicker Problem?)

**Comment by friedrichweise** [comment]
<img width="1262" alt="screen shot 2017-12-13 at 16 48 30" src="https://user-images.githubusercontent.com/7392490/33947745-855c3fae-e025-11e7-82cd-76604457140f.png">

(Problem mit Karte?)

**Comment by kakenbok** [comment]
hin und wieder spinnt unser geoservice und wirft eine 422 - Google API error: over query limit. dann wird auf dem item der geocode auf '' gesetzt. hier könnten wir entweder den service anpassen, dass er nicht mehr über das limit kommt ... oder aber wir fangen den fehler im UI ab und setzen dann eben nicht neue daten.

**Comment by kakenbok** [comment]
hab jetzt eingebaut, dass beim fehlschlag des initialen ladens der geocodes die item lon/lat werte nicht mehr auf null gesetzt werden: c14f64471eb50238662372953aaef74b829afb54

**Comment by kakenbok** [comment]
sowie: der api-geocoder cached jetzt seine aufrufe lokal in einem hash (wird mit jedem restart resettet, sollte aber ausreichen): 688df6997511e37b8f747e3ad56906554ffed840

**Comment by kakenbok** [comment]
@friedrichweise wie kommt der date-fehler zustande?

**Comment by friedrichweise** [comment]
Lag an invaliden Event Einträgen. Mit gültigen Einträgen kann ich den Fehler nicht mehr reproduzieren.

**Comment by kakenbok** [comment]
Siehe auch hier: dcbb354efe3b078ab280f2059c7018265483c5d1
