### ISSUE TITLE
Als Redakteur möchte ich das Hinzufügen eines neuen Eintrags abbrechen können.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#41]
abbrechen button X auch in formular für neuen Eintrag. bisher gibt es nur beim Edit-Formular oben rechts ein X. evtl kann man das X aber auch durch den allgemeinen Zurück button < ersetzen.

- [x] alle temporären models gelöscht
- [x] raise confirmation if dirty
- [x] redirect zur LETZTEN seite (wo plus button gedrückt wurde)

**Comment by kakenbok** [comment]
cancel creation is possible anyway. friedrich and me decided to issue a warning in the case the user is about to leave a dirty form.

**Comment by friedrichweise** [comment]
Blocked by #66

**Comment by kakenbok** [comment]
Follow-Up-Bug:
1. Create Event
2. Type in some title
3. Hit Cancel
->
Popup notification appears, never disappears, page reload necessary

**Comment by kakenbok** [comment]
follow up bug fixed along with this story.

**Comment by kakenbok** [comment]
friedrich, please review and test

**Comment by friedrichweise** [comment]
After saving an entry the dialog appears because of #66 (the attached models contact-info and location are not marked as saved).
We have to fix #66 in order to get this story done.

**Comment by kakenbok** [comment]
i would say, #66 and this #41 are independent from each other. cancelling adding an entry works fine. to be right, i did add an ugly quick fix for #66: 5d46debb

**Comment by kakenbok** [comment]
there has been a follow-up bug with the history.back() action behind the cancel button:

history.back() has been called in any case, even when the confirm dialog has been shown and the route transition got cancelled. in result, the browser switched back to the former url while the page did not. fix: implementing a rough history tracking and going back to it's last route.

**Comment by kakenbok** [comment]
another bug appeared which caused a dialog when cancelling the editing of entries when those entries received their relations runtime (missing on server side). fixed by creating empty relations in editorga and editevent as well as a small fix in the cancel-entry-edit-mixin.

**Comment by kakenbok** [comment]
no we got into troubles with saving entries that exists on the server but did not have annotations. for that case we now track all annotations found initially and set them back in rollback(). this is all a huge pain an did cost for today about 7 hours.

**Comment by kakenbok** [comment]
not blocked any longer with client hack for #44

**Comment by felixkamille** [comment]
bitte auch heutiges kommentar in #90 beachten (Überschneidung von erfolgreichem Speichern und Abbrechen)

**Comment by kakenbok** [comment]
should be fixed with the latest hack for #66 @friedrichweise  please test

**Comment by friedrichweise** [comment]
Everything works as expected.
Please keep in mind: Changing the #66 hack could affect this behaviour.

**Comment by kakenbok** [comment]
currently slightly broken due to changes in route-history service. "cancel" must not trigger "goBack".

**Comment by kakenbok** [comment]
ok refactored. der cancel button geht jetzt nicht mehr auf history back sondern in eine action mit dialog. wenn 'yes', erst dann wird history back getriggert.

**Comment by friedrichweise** [comment]
@kakenbok : Ready for acceptance test ? Or are we still waiting until the tests are written properly ?

**Comment by kakenbok** [comment]
ready for testing ... and there is also possibility to setup automated acceptance tests ...
