### ISSUE TITLE
Kontaktdaten-Wiederverwendung funzt nicht

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#413]
Man setze den Haken eines Kindeintrags um "fehlender Felder mit Angaben der Elternorga zu ergänzen", speichert und es wird nicht übernommen. Das Flag wird scheinbar auch nicht gesetzt.

Zu testen bspw. hier:
https://backend.afeefa.de/orgas/4432?tab=contactTab

**Comment by kakenbok** [comment]
das flag wird bzw. wurde wohl gesetzt, jedoch fehlte eine automatische aktualisierung des betreffenden eintrags im frontend-cache. mittlerweile gibt es diese funktion für das backend 2 sowieso nicht mehr.
