### ISSUE TITLE
Deployment mit Docker

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#414]
Da wir uns für Docker entschieden haben, müssten wir nun unsere Deploymentprozesse durchdenken. Wir haben mit dem automatischen Deployment des Frontend-Codes im letzten Jahr sehr gute Erfahrungen gemacht.
Der Ruby Code wurde über Capistrano auf den Server geschoben. Das hat technisch immer einwandfrei funktioniert.
Ich plädiere jedoch für eine Angleichung auf ein automatisiertes Deployment aller unserer Services (sowahl API's als auch UI's). Gerade unter dem Gesichtspunkt, dass wir jetzt auch Services in Node entwickeln ergibt die Capistrano-Ausnahme wenig Sinn.

@Stunkymonkey: Welche Hürden treten denn beim Deployment unseres Frontend-Codes im Kontext von Docker auf? Aktuell machen wir nicht viel mehr als ein `git pull` und ein `npm run build`.

@stevereinke: Wie schätzt du die Lage des API-Deployments ein? Sprichst du dich weiterhin gegen eine automatisierte Lösung aus? Wir könnten auch über Git Tags zum Auslösen des Deployments nachdenken. Außerdem wird es auf dem neuen Server eine dedizierte `stage`-Umgebung geben.

**Comment by Stunkymonkey** [comment]
> Welche Hürden treten denn beim Deployment unseres Frontend-Codes im Kontext von Docker auf? Aktuell machen wir nicht viel mehr als ein git pull und ein npm run build.

an sich macht das docker-setup dann `git pull` und `npm run build`
es würde sich nicht viel ändern

was ich nicht weiß ob sich capistrano gut mit docker kombinieren lässt. Das macht für mich aber auch kein Sinn das zu kombinieren.

**Comment by stevereinke** [comment]
Capistrano macht im Zusammenhang mit Docker keinen Sinn mehr, da reicht das auschecken via git und das Hinterlegen der notwendigen configs.

**Comment by stevereinke** [comment]
wie ist hier der stand? verfolgen wir das noch?

**Comment by Stunkymonkey** [comment]
soweit ich weiß ja
allerdings wollten wir erstmal soweiso auf den neuen server migrieren #407

**Comment by friedrichweise** [comment]
Können wir das nochmal diskutieren? Ich stehe der Docker Idee mittlerweile kritisch gegenüber. Der Serverumzug zieht sich jetzt bereits über Monate. Ich würde die Priorität erstmal auf den Abschluss der Migration legen. Außerdem fehlt uns im Team noch die Erfahrung für Docker. Somit währe eine Betreuung damit nur eingeschränkt möglich. Was sind eure Meinungen?

**Comment by Stunkymonkey** [comment]
der punkte mit der Erfahrung ist auch der größte Punkte, der für mich gerade dagegen spricht.

gerade wenn man neu in euer Team kommt, will man eigentlich nur den Code verstehen müssen, wenn man dafür aber erst mal docker lernen muss, wird das einfach verkompliziert. Und hiermit kann man bestimmt auch Leute abschrecken, die nicht so wahnsinnig viel Zeit bei Afeefa verbringen. Die werden dann vielleicht sagen, dass ihnen das zu viel Aufwand ist und so verliert ihr sie.
Also für den Development-Prozess bin ich fast der Meinung, dass das aktuelle so fast besser ist. Klar passieren kleine Fehler, aber man lernt dadurch auch viel über sein eigenes System.

Ich würde erst mal alles migrieren(was anscheindn nicht nur die 2 apis sind...) und dann das docker-Thema nochmal besprechen.

**Comment by friedrichweise** [comment]
Alles klar. Somit ziehen wir alle Services vorerst **ohne** Docker um.
