### ISSUE TITLE
Wisdom API auf Server installieren

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#443]

**Comment by Stunkymonkey** [comment]
welche api meint ihr genau? google gibt mir das [hier](https://github.com/gophergala/wisdom)
wozu braucht ihr das?

**Comment by friedrichweise** [comment]
https://github.com/AfeefaDe/afeefa-wisdom-api
Ein Microsservice zum Verwalten unseres Wissensportals.

**Comment by Stunkymonkey** [comment]
ist getan auf port 3010
