### ISSUE TITLE
tinymce font not found after build reorganisation

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#446]

**Comment by friedrichweise** [comment]
https://www.tinymce.com/docs/advanced/usage-with-module-loaders/

**Comment by friedrichweise** [comment]
https://github.com/tinymce/tinymce/issues/2836

**Comment by friedrichweise** [comment]
Es scheint lediglich ein Problem mit den Fonts zu geben. Styles und Font werden richtig importiert. Jedoch kommen die Fonts von `chapters/static/fonts/`. Diese werden dann von der CSS Datei nicht korrekt importiert. 
Fehlermeldungen kommen auch, wenn wir in `app.scss`
`@import '../../../node_modules/tinymce/skins/lightgray/skin.min.css';`
durch 
`@import '../../../node_modules/tinymce/skins/lightgray/skin.min';`
ersetzen.
