### ISSUE TITLE
Share contacts

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#474]
- [x] entry.contact_id 
- [ ] api endpunkt zum linken/unlinken eines kontaktes
- [ ] get entry.contacts → aktuell zumindest workarounded (siehe contacts-Helper in HasContacts) ;-)
- [x] migration anpassen
- [ ] contact type main und sub entfernen

**Comment by stevereinke** [comment]
gemeinsame Entscheidung: entry.contract_id statt contact_owners table

**Comment by stevereinke** [comment]
Stand, siehe letztes Commit am Branch (20180829_474_steve_share-contacts):
TODOs:
    * include it into orgas_controller and events_controller
    * test it
    * Does contact has an area?
