### ISSUE TITLE
Übersetzungen anzeigen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#48]
PhraseApp API: https://phraseapp.com/docs/api/v2/

PhraseApp Ruby gem: https://phraseapp.com/docs/developers/libraries-tools/

PhraseApp demo rails app: https://github.com/phrase/demo-rails-app

**Comment by kakenbok** [comment]
Could you please create independently manageable tasks/stories from this issue?
