### ISSUE TITLE
opening hours not available

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#516]
the attribute `openingHours` needs to be included into the JSON output. it's probably a mapping from `contact.openingHours` to `openingHours` like the other contact attributes, which are served as a root level attribute of the entry's JSON output.

**Comment by felixkamille** [comment]
beispiel, in dem die öffnungszeiten nicht angezeigt werden, aber im backend eingetragen sind: https://leipzig.afeefa.de/project/4615-willkommenszentrum-leipzig

**Comment by stevereinke** [comment]
fixed with https://github.com/AfeefaDe/afeefa-frontend-api/commit/857c1c7d0243bb4a909e2bd965f49872dfeab1b7
Deployment to live system was already done.
