### ISSUE TITLE
create and update orga and event using one request for action

### ISSUE THREAD

**Issue by stevereinke** [AfeefaDe/afeefa-backend-ui#52]
create and also update of an orga and also of an event should be possible using one request including the object attributes and attributes of nested objects.

**Comment by stevereinke** [comment]
there was a bug creating an event without orga

**Comment by kakenbok** [comment]
@dataprovider(mit orga, ohne orga, invalid data, valid data, mitohne....)
test_create_event()
:D

**Comment by friedrichweise** [comment]
Fails with error:
```
Internal Server Error: undefined method `[]' for nil:NilClass
```
