### ISSUE TITLE
Auf meinem Desktop PC möchte ich effizient navigieren.

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#59]
Current development: `dev-friedrich-desktop`

- [x] indicate current route in navigation-sidebar
     - [x] restructure routes
- [x] cleanup and rename afeefa-navigation (answer `@question`)
- [x] add link to search
- [x] add user/logout section in sidebar
- [x] fix breadcrumb and mobile navigation with new route structure
- [x] fix tests

**Comment by friedrichweise** [comment]
After restructuring the routes I'm struggling with the navigation service written by @kakenbok

**Comment by kakenbok** [comment]
ja, der ist sehr, sehr auf den zweck hin geschrieben. routen können z.b. nur maximal die tiefe 2 haben. was brauchst du?

**Comment by friedrichweise** [comment]
Du kannst dir mal den `dev-friedrich-desktop` branch anschauen. Ich habe die Routen umstrukturiert. Sonst besprechen wir das mal am Mittwoch.

**Comment by kakenbok** [comment]
okay, fixed. führ bitte immer auch die tests mit aus. derzeit sind alle generierten route-tests rot. bis mittwoch.

**Comment by kakenbok** [comment]
klappt super, sieht super aus. felix, bitte abnehmen :-)

**Comment by kakenbok** [comment]
code hab ich auch gecheckt 1+
