### ISSUE TITLE
Klick auf Kontakt-Telefonnummer wählt Nummer (nur mobil)

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#6]
evtl per `<a href="tel:18475555555">1-847-555-5555</a>`

**Comment by friedrichweise** [comment]
Sollte nochmal mit dem Backend abgesprochen werden. Es dürfen zum Beispiel keine `/` vorkommen:
https://css-tricks.com/the-current-state-of-telephone-links/

**Comment by kakenbok** [comment]
Duplicates #37
