### ISSUE TITLE
Publish Button

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#60]

**Comment by HagenBeelitz** [comment]
über state transition model nachedenken

**Comment by friedrichweise** [comment]
The `stateTransition` attribute should not be a part of the frontend data structure. In my opinion the `state` attribute should be a simple boolean.

**Comment by HagenBeelitz** [comment]
- [ ] add Button
- [ ] change stateTransition in states-forms.hbs
- [ ] fix handle error if publish state is changed
