### ISSUE TITLE
validate category on create of entry

### ISSUE THREAD

**Issue by stevereinke** [AfeefaDe/afeefa-backend-ui#64]
The backend should validate an empty category on **CREATE**

**Comment by kakenbok** [comment]
Currently we get the message "Kategorie - muss ausgefüllt werden" for both orgas and events.

**Comment by kakenbok** [comment]
test mit event ohne kategorie: servermessage =  "Kategorie - muss ausgefüllt werden" :thumbsup:

**Comment by kakenbok** [comment]
orga mit event ohne kategorie: servermessage =  "Kategorie - muss ausgefüllt werden" :thumbsup:

=> tested and confirmed

**Comment by stevereinke** [comment]
also können wir das schließen?

**Comment by stevereinke** [comment]
test für create schreiben, bei dem keine associations dran sind, dann wird möglicherweise das zweite save im base_resource übersprungen, dann könnte man evtl. eine orga ohne category speichern...

**Comment by stevereinke** [comment]
Das lösen wir mit dem Ausbau des json-api-resources gem
