### ISSUE TITLE
Improve frontend performance

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#65]
There are several ways to minify the request amount and size:
- [x] load Todos only in `protected.js` model
- [ ] lazy load orgas/todos/events: Only load first 5 items that are required to properly render the dashboard
- [x] remove unused information from the request (links...) (#92)
- [x] to many request for "All Todos" (#88)

**Comment by kakenbok** [comment]
@see #90 for "too many requests for "all todos""

**Comment by kakenbok** [comment]
Again a kind request to refiddle huger tasks into smaller ones. I did for the #90 in response to the Friday's discussion protocol. Wasn't aware of this cover-task.

**Comment by friedrichweise** [comment]
Moved into #88 and #92.
