### ISSUE TITLE
Save relationship entries after create/edit of entry

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#66]
After saving an entry with the "ember-data-save-relationships" hack the associated models are not marked as saved. Additionally they don't have the correct id.
**Expected JSON:**
````
data: {
  relationships: {
    annotations: [data: {...}]
  }
}
````
**From Server:**
````
data: {
  relationships: {
    annotations: [link: {self:'...'}]
  }
}
````
We could either change the JSON format or customize the Ember serializer.

**Comment by friedrichweise** [comment]
At least the returned object should contain **key** and **type** to map the model to the local model.

- [ ] add type and key to returned json
- [ ] modify custom ember serializer

**Comment by stevereinke** [comment]
sag mal, könntest du dir auch die daten aus den mittels includes gelieferten objekten mappen?

**Comment by friedrichweise** [comment]
That would require a new request for each model.  Alternatively I could reconstructed the **link** URL. But that isn't a pretty solution at all.

**Comment by stevereinke** [comment]
elements delivered via include tag should not require a new request for  each model, should it?

**Comment by friedrichweise** [comment]
No. As far as I understood the spec. that is the whole point of the `include` tag.

**Comment by stevereinke** [comment]
Let's test it.

**Comment by friedrichweise** [comment]
Regarding to this [documentation](https://emberigniter.com/saving-models-relationships-json-api/) the internal `__id__` attribute has to be passed back by the server.

**Comment by kakenbok** [comment]
releated to #41 - cancel add
there is now a dialog (abbrechen: ja/nein), if the route changes and the entities are still marked dirty. what works for new items gets problematic when editing entries. requests are sent to the server using this bulk-hack but not instantly rewritten to the ember-data store, so all releations are still marked dirty although sucessfully saved on the server.
idea: reload entity completely after each save operation or replace entity with the data contained by the save-response (if there is an entity representation returned).

**Comment by kakenbok** [comment]
i just added the "reload relations before transition" ugly hack here: 5d46debb

**Comment by stevereinke** [comment]
[] deliver __id__ via api for syncing models at the ember client

**Comment by friedrichweise** [comment]
- [ ] Move id key into attributes

**Comment by stevereinke** [comment]
should be done

**Comment by stevereinke** [comment]
now we always return all nested models in relations and so the rails server takes 20-30 sec to deliver the answer for the todo dashboard request

i suggest we should cancel the todo concept and use filters on orgas and events to get the todo view

what about  that?

**Comment by kakenbok** [comment]
mit dem letzten commit sind die relations leider doch nicht sinnvoll enthalten. hier fehlen jetzt die attribute (ich sehe nur id und type) bzw. am ende die "included_data", falls id und type nur eine referenz darstellen sollen. included data ist zwar da hat aber nur annotations und categories.

```
locations:
{links: {self: "http://localhost:4200/api/v1/orgas/1337/relationships/locations",…},…}
data:[{type: "locations", id: "2000"}, {type: "locations", id: "2001"}]
0:{type: "locations", id: "2000"}
id:"2000"
type:"locations"
1:{type: "locations", id: "2001"}
id:"2001"
type:"locations"
```

`

**Comment by kakenbok** [comment]
beim speichern werden die relation data für contact und location leider noch nicht mitgeschickt (nur id und type), sodass beim speichern durch ember kein matching erfolgt und die daten im client dirty bleiben. ich kann im postman den PATCH faken und einen querystring /api/v1/orgas/1336?include=contact_infos,annotations,locations mit übergeben. dann bekomme ich auch die included data. ABER: ember erlaubt no way querysrings bei PATCH.

lösung: bei edit entry bitte im response immer include annotation, contacts, locations

**Comment by stevereinke** [comment]
das is so sinnlos, friedrich hatte gehofft, dass es reichen würde, diese attribute mitzuschicken, um mittzuteilen, dass das objekt gespeichert uwrde...
zum kotzen...
dann müssen wir da nochmehr dran frickeln und anscheinend alle attribute ausgeben....
aber gut finde ich das ni...

**Comment by kakenbok** [comment]
ember hack für #66 funktionierte nicht für CREATE, jetzt schon. nach update/create werden jetzt alle relations (location, contact, annotation) als 'root.loaded.saved' gespeichert (falls schon vorhanden) oder aber gelöscht (falls erst erstellt). wenn gelöscht, werden sie im view wieder automatisch geladen.

**Comment by friedrichweise** [comment]
It seems to work for `CREATE` actions. Although there are two `locations` and two `contactInfos` in the local ember store. One of them is saved, the other has `hasDirtyAttributes `. Both of them have a valid id from the server.

Regarding the `PATCH` action: Changing attributes of the models works just fine. Related models (like contactInfo and location) are not marked as saved.

**Comment by friedrichweise** [comment]
Blocked until @kakenbok has implemented unit tests.

**Comment by kakenbok** [comment]
should be fixed now. could you please test, friedrich? there are problems in detectíng the date picker changes.

**Comment by friedrichweise** [comment]
Works as expected.
