### ISSUE TITLE
Improve Code quality and consistency

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#67]
- [ ] use camel/underscore/dash in **API AND UI**
- [ ] a better way to define the output of a model attribute (Date, annotation etc.) - `entry-detail.js`, `entry-list-item.js`
- [ ] 404 page for unknown routes
- [ ] clean up bower and npm
- [ ] update ember and ember-data
- [ ] same licence for every github repo
- [ ] check JSHint errors/warnings

**Comment by kakenbok** [comment]
Could you please refactor this bucket-task into smaller independent chunks?

**Comment by friedrichweise** [comment]
I created smaller issues for all relevant points. 
Checking JSHint should be a part of our daily development workflow.
