### ISSUE TITLE
Als Redakteur möchte ich ortsunabhängige Dinge einstellen

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#73]
es gibt schon in der jetzigen datenbasis einträge, die keinen ort haben müssen, zb börseneinträge oder auch sammeleinträge, die als elternteil nur eckdaten ihrer kinder kapseln und selbst keinen ort haben (zb SLUB allgemein (kein ort, nicht veröffentlicht) > zweigstellen (mit ort und veröffentlicht))

**Comment by kakenbok** [comment]
@see #45

**Comment by kakenbok** [comment]
- [x] Orga anlegen ohne Ort klappt
- [x] Event anlegen ohne Ort klappt
- [x] Orga ändern ohne Ort klappt
- [x] Event ändern ohne Ort klappt

**Comment by kakenbok** [comment]
bitte abnehmen, wurde erfolgreich getestet
