### ISSUE TITLE
Changes still persisted in ember-data after cancellation of editing

### ISSUE THREAD

**Issue by KopierKatze** [AfeefaDe/afeefa-backend-ui#76]
Wenn man einen vorhandenen Eintrag verändert und Fehler angezeigt werden (zB. Beschreibung zu lang), werden die gemachten Änderungen in Feldern wie zB. Kontaktdaten lokal noch angezeigt. 
Bei F5 werden sie wieder neu geladen und korrekt angezeigt.

**Comment by KopierKatze** [comment]
Das gilt auch, wenn man das Editieren abgebrochen wird. HasDirtyAttributes ist true aber der Sync wird abgebrochen.

**Comment by kakenbok** [comment]
transactions should/could/hopefully fix this: http://stackoverflow.com/questions/10936007/revert-change-to-ember-data-model

**Comment by friedrichweise** [comment]
blocked by #66

**Comment by friedrichweise** [comment]
@kakenbok There is no documentation for transactions in ember-data. I couldn't find any public API docs at all.

**Comment by kakenbok** [comment]
fixed, friedrich please review
