### ISSUE TITLE
Bug: Legacy desciptions too long after migration

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#77]
Migrated orgas/events do have to a major extent a significant higher text length than our new 350 char limit. e.g. 163 orgas with > 350 while 11 orgas with < 350

how can we handle this, there is obviously a need for larger descriptions.

**Comment by kakenbok** [comment]
There are different ideas:

* Provide a read more link and set char limit up to 2500
* Allow existing entries to have more than 350 chars but not newly created ones
** Validation of length then happens only to creation of entries
* Rewrite existing descriptions to fit into the 350 restriction
* ...

**Comment by friedrichweise** [comment]
We are using two separated fields for long and short description.

**Comment by kakenbok** [comment]
can be closed probably
