### ISSUE TITLE
Bug: 90% of entries get "invalid" annotation after migration from Neos

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#78]
- [ ] hausnummer weghauen
- [ ] kontakt mail/phone should not be more than 1 annotation and could be related to the model instead of the actual attribute (currently attached to both fields)
- [ ] events do not need contact information
- [ ] editors must be able to give multiple events the same name
- [ ] legacy descriptions must be allowed to take more than 350 chars
- [ ] legacy titles must be allowed to take more than 150 chars

**Comment by kakenbok** [comment]
@felixkamille please make a decision on how to proceed with these db-model changes.

**Comment by kakenbok** [comment]
`select distinct(detail), count(detail) from annotation_able_relations group by detail`

annotation_able_relations
---
| detail | count(detail) | 
| - | -: | 
| Beschreibung ist zu lang (mehr als 350 Zeichen) | 296 | 
| Beschreibung muss ausgefüllt werden | 94 | 
| Date start muss ausgefüllt werden | 6 | 
| E-Mail-Adresse Mail-Adresse oder Telefonnummer muss angegeben werden. | 156 | 
| Hausnummer fehlt | 385 | 
| Kontaktperson muss ausgefüllt werden | 225 | 
| Telefon Mail-Adresse oder Telefonnummer muss angegeben werden. | 156 | 
| Titel ist bereits vergeben | 31 | 
| Titel ist zu lang (mehr als 150 Zeichen) | 2 | 
| Titel muss ausgefüllt werden | 17 |

**Comment by kakenbok** [comment]
```
select distinct(detail), entry_type, count(detail)
from annotation_able_relations
group by detail, entry_type
order by entry_type
```

annotation_able_relations
---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| Beschreibung ist zu lang (mehr als 350 Zeichen) | Event | 133 | 
| Hausnummer fehlt | Event | 137 | 
| Kontaktperson muss ausgefüllt werden | Event | 78 | 
| E-Mail-Adresse Mail-Adresse oder Telefonnummer muss angegeben werden. | Event | 88 | 
| Telefon Mail-Adresse oder Telefonnummer muss angegeben werden. | Event | 88 | 
| Date start muss ausgefüllt werden | Event | 6 | 
| Titel muss ausgefüllt werden | Event | 2 | 
| Beschreibung muss ausgefüllt werden | Event | 3 | 
| Titel ist bereits vergeben | Event | 10 | 
| Titel ist zu lang (mehr als 150 Zeichen) | Event | 2 | 
| \N | Event | 0 | 
| Beschreibung muss ausgefüllt werden | Orga | 91 | 
| Hausnummer fehlt | Orga | 248 | 
| Beschreibung ist zu lang (mehr als 350 Zeichen) | Orga | 163 | 
| Kontaktperson muss ausgefüllt werden | Orga | 147 | 
| E-Mail-Adresse Mail-Adresse oder Telefonnummer muss angegeben werden. | Orga | 68 | 
| Telefon Mail-Adresse oder Telefonnummer muss angegeben werden. | Orga | 68 | 
| Titel muss ausgefüllt werden | Orga | 15 | 
| Titel ist bereits vergeben | Orga | 21 |

**Comment by kakenbok** [comment]
`select count(*) from orgas` 266
`select count(*) from events` 141

**Comment by kakenbok** [comment]
annotation_able_relations
---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| E-Mail-Adresse Mail-Adresse oder Telefonnummer muss angegeben werden. | Event | 95 | 
| Telefon Mail-Adresse oder Telefonnummer muss angegeben werden. | Event | 95 | 
| Start-Datum muss ausgefüllt werden | Event | 5 | 
| Titel muss ausgefüllt werden | Event | 1 | 
| Titel ist zu lang (mehr als 150 Zeichen) | Event | 2 | 
| \N | Event | 0 | 
| E-Mail-Adresse Mail-Adresse oder Telefonnummer muss angegeben werden. | Orga | 96 | 
| Telefon Mail-Adresse oder Telefonnummer muss angegeben werden. | Orga | 96 | 
| Titel muss ausgefüllt werden | Orga | 13 | 
| Titel ist bereits vergeben | Orga | 22 | 
| \N | Orga | 0 |

**Comment by kakenbok** [comment]
```
select distinct(detail), entry_type, count(detail)
from annotations
group by detail, entry_type
order by entry_type
```

annotations
---
| detail | entry_type | count(detail) | 
| - | - | -: | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Event | 34 | 
| Titel muss ausgefüllt werden | Event | 2 | 
| Start-Datum muss ausgefüllt werden | Event | 7 | 
| Titel ist zu lang (mehr als 150 Zeichen) | Event | 3 | 
| Titel muss ausgefüllt werden | Orga | 11 | 
| Titel ist bereits vergeben | Orga | 34 | 
| Kurzbeschreibung ist zu lang (mehr als 350 Zeichen) | Orga | 10 |

**Comment by kakenbok** [comment]
Wir haben jetzt 44 Dinger mit zu langer Kurzbeschreibung. Wie gehen wir damit um?

**Comment by stevereinke** [comment]
Titel bereits vergeben gibt es auch 34 Mal, was passiert damit?

**Comment by stevereinke** [comment]
Vererbte Informationen müssen in der Migration noch korrekt übernommen werden.

**Comment by felixkamille** [comment]
__zu lange Kurzbeschreibungen__ bleiben als solche markiert und müssen später von den Redakteuren berichtigt werden.

__gleiche titel__ bei der migration einfach durchnummerieren. also _Lala_ und _Lala 2_ und _Lala 3_ etc.
Ginge das?

__Vererbungen__ diskutieren wir beim nächsten sprint
