### ISSUE TITLE
auto deploy backend-api dev and backend-ui dev on commit

### ISSUE THREAD

**Issue by stevereinke** [AfeefaDe/afeefa-backend-ui#79]
- [x] api script
- [x] npm script for ui

**Comment by friedrichweise** [comment]
We are not implementing automated deployment of the afeefa-backend-api and continue use capistrano.

**Comment by friedrichweise** [comment]
Fix for Vue Frontend

**Comment by friedrichweise** [comment]
@Stunkymonkey: review the CI script and fix timeout issue.

**Comment by Stunkymonkey** [comment]
will have a look at it, but at the weekend

**Comment by friedrichweise** [comment]
Working. Improvements:
- check if Shell gets closed properly
- fix Github Timeout issue

**Comment by Stunkymonkey** [comment]
- [X] shell gets closed properly

**Comment by Stunkymonkey** [comment]
not done yet:

- [ ] fix Github Timeout issue
