### ISSUE TITLE
Error handling for undefined routes

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#83]
Create 404 page or redirect to dashboard.

**Comment by kakenbok** [comment]
:thumbsup:

**Comment by friedrichweise** [comment]
Reproduce: Visit undefined route after login. 
The routes for invalid sessions are already been managed by ember-simple-auth.

**Comment by felixkamille** [comment]
hält einer kreativen URL Befeuerung stand und leitet mich zuverlässig zum Dashboard um. Die URL wird auch zurückgesetzt, was schön ist. Eine Meldung wäre noch gut. Daraus mache ich mal eine neue Story und schließe hier.
