### ISSUE TITLE
Bug: Todos list loads billions of annotations

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#88]
Just open todos page and watch network inspector. 1 annotation for each todo gets loaded.

Idea: include annotations in api resource request.

**Comment by friedrichweise** [comment]
The `include` solution is not working because the API cant query for entries using include.
@stevereinke what are your thoughts ? Fix the server or create an Ember workaround ?

**Comment by stevereinke** [comment]
copy from slack:
@steve wegen der save relations: die response attributes koennen im included node mitgeliefert werden. Wie beim Laden. Im entity selbst reicht ein Eintrag unter relations mit type und id wie gehabt. Die __id__ gehoert dann auch ins included.item.attributes wenn das was einfacher macht fuer dich. #66

**Comment by stevereinke** [comment]
we refactured and optimized the api index actions for todos, entries, orgas, events
so we got much better response times

let's find out if that was enough to do
