### ISSUE TITLE
Bug: Textarea does not enlarge to text on focus

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#89]
Open an entry with long description. Click pen to got the edit view. Description field appears with 3 rows. Click into field: Textarea with just 3 rows appears. Will not enlarge until you start typing in such as using an arrow key.

**Comment by friedrichweise** [comment]
Seems to be related to https://github.com/Dogfalo/materialize/issues/1503

**Comment by kakenbok** [comment]
checked an found to be great!
