### ISSUE TITLE
ROOT ORGA als parent nicht akzeptiert bei new orgas/new

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#9]
man kann einen neuen eintrag erst speichern, wenn man einen partent ungleich "ROOT ORGA" auswählt

**Comment by friedrichweise** [comment]
Soweit ich informiert bin, ist das auch so gewollt. Die ROOT ORGA sollte im Frontend immer ausgeblendet werden (#7)

**Comment by friedrichweise** [comment]
Wenn kein parent ausgewählt wird, setzt das Backend automatisch die "ROOT ORGA". Somit wird die ROOT ORGA immer ausgeblendet.
