### ISSUE TITLE
Bug: Add entry redirects to dashboard not to view

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#90]
Add entry (orga/event) -> Redirects to dashboard

Expected: Redirects to View

**Comment by felixkamille** [comment]
Das würde ich mal als weiteren Bug bezeichnen, auch wenn wir uns gegen die bug-bezeichnung ausgesprochen haben, solange es nicht um released software geht. jedenfalls:

ich habe einen neuen eintrag angelegt und wie auf dem screenshot zu sehen ausgefüllt. beim klick auf speichern ratterte es und ohne dass der View wechselte passierte folgendes:
1. der _Löschen_ Button kam hinzu
2. die positive Meldung "Ihr Eintrag wurde gespeichert" erschien
3. die letzte Meldung wurde von der "Abbrechen" Nachfrage ersetzt > ich wählte _nein_
4. ich verblieb im formular und drückte erneut auf _speichern_ und gelangte erwartungsgemäß auf die View-Ansicht meiner neuen Orga und erhielt eine positive Nachricht, dass gespeichert wurde

Irgendwie springt da der _Abbrechen-Mechanismus_ an, wenn ich einen neuen Eintrag das erste mal speichern/ erstellen möchte.
![image](https://cloud.githubusercontent.com/assets/1052429/22104150/3c454b92-de3e-11e6-850f-8a7dc1ff393b.png)

**Comment by kakenbok** [comment]
das kann ich nachvollziehen. wir hatten gestern backend-änderungen, möglicherweise ist dadurch das ember-data-handling etwas kompromittiert. da muss es auf den millimieter genau passen.

**Comment by kakenbok** [comment]
fixed mit der letzten version von hack #66 (update ember relations after save)

**Comment by kakenbok** [comment]
please test @HagenBeelitz

**Comment by HagenBeelitz** [comment]
beim ersten speichern einer neuen Orga oder eines neuen Events wird fälschlicherweise der Abbruch Dialog aufgerufen
