### ISSUE TITLE
As an editor I would like to see the parent orga in detail view

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#91]
Orgas->View Orga, if there is a parent orga, it should be displayed. By the time of writing, there are only suborgas supported.

**Comment by friedrichweise** [comment]
Any ideas on visualisation (@felixkamille) ?  Indentation or icons ?
This looks pretty boring:
<img width="530" alt="screen shot 2017-01-13 at 16 26 22" src="https://cloud.githubusercontent.com/assets/7392490/21935288/42c4f05c-d9ad-11e6-9ed9-8b735e5a4293.png">

**Comment by felixkamille** [comment]
↑ Übergeordnete Orga
...

↓ Untergeordnete Orgas
...

den bedarf hatte ich auch gleicht verspürt. erstmal einfach so easy, würde ich vorschlagen. außerdem würde ich diese relationen eindeutiger von den direkten eigenschaften des eintrags trennen, also z.B. das "material" unter dem _Aktivieren_ button abschneiden und die ober- und unterorgas in ein neues material setzen.

öffne das ticket wieder, wenn du das machen willst, ansonsten kannst du es auch so lassen.
