### ISSUE TITLE
Als Redakteur möchte ich bei Events eine Endzeit (Datum und Uhrzeit) angeben, wenn das Event eine explizite Endzeit hat.

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#93]
- [x] 2 fields (date, time) for each date type (start, end)

- [x] date_start default: day = CURRENT_DAY, "add time" icon present
- [x] if time is set, display [x] else display clock icon which opens time picker
- [x] initial time (add time clicked) always next full hour, max 23:00
- [x] date_end default: day = "gleicher tag", "add time" icon present
- [x] if time is set, display a remove button which sets "has_time[start|end]" to false

- [x] if day_start == day_end or day_end not set -> display "gleicher tag" for day_end, when changing day_start -> keep "gleicher tag"
- [x] click on displayed day opens date picker, regardless if its a date or "gleicher tag"
- [x] if day_start == day_end and time_end set -> save date_end, else if time_end not set save date_end = null

**Comment by kakenbok** [comment]
Tasks:
- [ ] Steve please add two fields: has_time_start and has_time_end, both default false

**Comment by stevereinke** [comment]
- [x] deliver and accept has_time_start via api
- [x] deliver and accept has_time_end via api

**Comment by HagenBeelitz** [comment]
test user input:
- [ ] end date >=  start date

**Comment by felixkamille** [comment]
Warum wird hier dieser Fehler geworfen? Die Angaben sind doch korrekt, oder?
![image](https://cloud.githubusercontent.com/assets/1052429/22389008/ca9bd928-e4e3-11e6-92d4-f8f2a8a69dc4.png)

**Comment by kakenbok** [comment]
- [x] alles getestet wie oben. works like a scham!

**Comment by kakenbok** [comment]
- [ ] Neues Event ohne Enddate speichern wirft Client-Error: "Cannot read property 'getDate' of null" - entry_form

**Comment by kakenbok** [comment]
- [x] same day + end time sends correct date to server
- [x] same day without end time sends null to server
- [x] different end day without end time sends corrent date to server
- [x] different end day + end time sends corrent date to server
