### ISSUE TITLE
Als Redakteur möchte ich eine Startuhrzeit eines Events angeben, damit die Besucher wissen, wann sie da sein sollen.

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#95]
- [x] clock icon
- [x] when clock clicked time appears (current time)
- [x] time is optional
- [x] time can be removed

**Comment by stevereinke** [comment]
- [ x ] deliver and accept has_time_start via api

**Comment by HagenBeelitz** [comment]
- [] picker should not work directly on the model

**Comment by felixkamille** [comment]
Kann nicht speichern. Ob mit oder ohne Startzeit.
![image](https://cloud.githubusercontent.com/assets/1052429/22389098/4090e66e-e4e4-11e6-9e24-24a5e3a11548.png)

**Comment by HagenBeelitz** [comment]
hast du das in einem Event oder einer Orga versucht? In der Orga wurde vor drei Tagen noch irrtümlicherweise der date picker angezeigt, dass würde erklären warum das dann nicht erlaubt ist, wenn die Orga keine Zeit hat. Der bug wurde gefixed. Kannst du diesen Fehler auf dem jetzigen Stand noch einmal reproduzieren?

**Comment by kakenbok** [comment]
- [x] alles getestet wie oben im startkommentar angegeben! works
