### ISSUE TITLE
Als Redakteur möchte ich ein Alert/Dialog mit ESC automatisch schließen.

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#96]
alert/dialog opens
hit esc
cancel actions executes

- [x] dialog
- [x] alert

**Comment by kakenbok** [comment]
moved to 0.3. by the way we started automated testing with dialog and alert

**Comment by friedrichweise** [comment]
The `.focus()` function is not working as expected. There is no focus for error messages on undefined routes and while the cursor is in the login form.

**Comment by kakenbok** [comment]
guck mal bitte in den dev, hier habe ich sehr viele fehler gefixt. am besten du mergest mal den dev in den friedrich: https://github.com/AfeefaDe/afeefa-backend-ui/commit/497576ad23ecf4f104821df9ae42902fe69bb7e6

**Comment by kakenbok** [comment]
oki das ist für das alert jetzt so gelöst, dass einfach auf das body-keydown gelauscht wird. das fokus-geraffel hab ich demnach entfernt. für den dialog ist es aber weiterhin drin, da gabs ja auch keine probleme bislang.
