### ISSUE TITLE
Liste von offenen Punkten bzgl. Styles erstellen

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#97]
- [ ] Liste offener Punkte
- [ ] evtl. Doku über schon vorhandene Styles

**Comment by friedrichweise** [comment]
## work in progress
* link color, style
* color of buttons: red, green...
* page templates to reduce code redundancy
* should we use the materialize grid ???
* document .mainCard (light, dark header...)
