### ISSUE TITLE
Als Redakteur möchte ich alle vergangenen Events einer Orga sehen

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#98]
... um einfach alte Daten wiederzuverwenden

- [x] in detail view
- [x] nicht sofort geladen
- [x] erst laden, wenn extra angefordert
- [x] events sind verlinkt

Erst nach #99 umsetzen (lange Listen paginieren)

**Comment by HagenBeelitz** [comment]
bug: [ ] neu erstellte events erscheinen erst beim neu laden in den orga events

**Comment by friedrichweise** [comment]
Bug fixing tracked in #145

**Comment by kakenbok** [comment]
Hier ein paar Comments zu https://github.com/AfeefaDe/afeefa-backend-ui/commit/3c6f6469d77904b3a894a8397ecdaa72e261077a

Außerdem könnte es sein, dass unsere Date-Sortierung gar nicht richtig funktioniert, weil sie über Date-Instanzen ausgeführt wird und hier === < und > nicht zieht. Würde gerne Tests dazu sehen.
Ich hatte die Sortierfunktionen einfach von Ember kopiert, wo wir mit Datestrings gearbeitet hatten (glaube ich).

**Comment by kakenbok** [comment]
tested mit 2 alten und neuen events, klappt. alte events von gerade vorhin bis übelst alt sortiert und neue events von demnächst bis sonstwann in der zukunft.
