### ISSUE TITLE
Als Redakteur möchte ich lange Listen paginiert navigieren

### ISSUE THREAD

**Issue by kakenbok** [AfeefaDe/afeefa-backend-ui#99]
- [x] Seitennavigation
- [x] Filter Items pro Seite, um Anzeige von allen zu ermöglichen

**Comment by kakenbok** [comment]
hey friedrich, magst du das noch schön machen (css?)

**Comment by friedrichweise** [comment]
Ja

**Comment by friedrichweise** [comment]
- [ ] CSS styling (@friedrichweise)
- [ ] create `entry-list` without pagination (e.g. for dashboard) (@kakenbok)

**Comment by kakenbok** [comment]
`{{entry-list instances=model.orgas attributes=model.attributes sortOrder='title:asc' pagination=true}}` - default = false

außerdem gibts noch pageSize: `{{entry-list instances=instances attributes=attributes sortOrder='createdAt:desc' pagination=true pageSize=5}}` - default = 15
